### ISSUE TITLE
Publish newest helm chart version 0.2.1

### ISSUE THREAD

**Issue by cabrinha** [cortexproject/cortex-helm-chart#104]
Lots of changes are currently in the master branch, which shows a chart version of 0.2.1, but this helm repo only offers version 0.2.0

```
❯ helm search repo cortex
NAME            CHART VERSION   APP VERSION     DESCRIPTION
cortex/cortex   0.2.0           v1.4.0          Cortex
```

Please publish the latest version of this chart to the helm chart repo: https://cortexproject.github.io/cortex-helm-chart

**Comment by cabrinha** [comment]
It would also be great to publish this chart to ChartCenter -- Allowing users to more easily find and deploy this chart: https://chartcenter.io/docs/inclusion.html

They would keep these versions up to date with no manual intervention.

**Comment by khaines** [comment]
Latest version of the chart should be in the repo index, once #108 is merged.

**Comment by cabrinha** [comment]
> Latest version of the chart should be in the repo index, once #108 is merged.

Awesome! Now, how about getting the chart included into ChartCenter? https://chartcenter.io/docs/inclusion.html

**Comment by khaines** [comment]
going to mark this as closed since the updated chart is now published
