### ISSUE TITLE
Values.clusterDomain for templates not working

### ISSUE THREAD

**Issue by webdz9r** [cortexproject/cortex-helm-chart#105]
It seems for any templates using Values.clusterDomain are ignored and are using cluster.local as the default value. I found this true on the follow template files: 
- cortex/templates/alertmanager-dep.yaml
- cortex/templates/querier-dep.yaml
- cortex/templates/ruler-dep.yaml
- cortex/templates/nginx-config.yaml

# configuration value
`clusterDomain: clarson`

# output from chart on: cortex/templates/nginx-config.yaml
`proxy_pass      http://cortex-distributor.cortex.svc.cluster.local:8080$request_uri;`

# Using helm template generation (ignore my bash variables)
`helm template cortex cortex-helm/cortex --version $CHART_VERSION -f config.yaml --create-namespace -n cortex > $APP_VERSION/install.yaml`

**Comment by webdz9r** [comment]
This seems to be addressed in pending #108

**Comment by khaines** [comment]
Should be addressed now
