### ISSUE TITLE
blocks_storage configuration, store gateway address?

### ISSUE THREAD

**Issue by runningman** [cortexproject/cortex-helm-chart#115]
I'm trying to setup blocks_storage with the helm chart. I have the `blocks_storage` config block setup for s3 based on some other examples I came across here. And I configured etcd as the kvstore.

The issue I'm facing is:
`level=error ts=2021-01-29T13:19:07.934930043Z caller=log.go:150 msg="error running cortex" err="failed to initialize querier for engine 'blocks': no store-gateway address configured`

I have tried setting the `store_gateway_addresses` to `cortex-store-gateway-headless:9095` (I have simplified the name here). This brings the pods up but they fail to actually connect:

```
level=error ts=2021-01-29T15:35:51.351902357Z caller=frontend_processor.go:61 msg="error processing requests" address=10.27.74.198:9095 err="rpc error: code = Unavailable desc = transport is closing"
```

What else might I be missing?

**Comment by kmeinster** [comment]
I think a bit more info might be handy, for example the logs of the store-gateway itself perhaps?

**Comment by arpitjindal97** [comment]
Here is working config:

```
config:
  querier:
    store_gateway_addresses: "dns+cortex-store-gateway-headless:9095"
```

It should be added to documentation, as well as default in `values.yml`
