### ISSUE TITLE
Point users to kvstore memberlist

### ISSUE THREAD

**Issue by SudoBrendan** [cortexproject/cortex-helm-chart#120]
Greetings,

I'm a new user of the chart and also new to Cortex, it took me a bit of digging to figure out `memberlist` was a standalone option for kvstore, and I wanted to offer some ideas about it:

`memberlist` isn't mentioned at the top of the README - which states an external kvstore is "required"; this appears false when using `memberlist`. I might suggest:
    - In addition to naming specific kvstores in the README, it might be best to link people to the [cortex docs on the issue](https://cortexmetrics.io/docs/architecture/#the-hash-ring). It's worth mentioning in the README that `memberlist` (while it has limitations) does not require additional architecture outside this chart for an MVP.
    - Making `memberlist` (instead of `consul`) the default kvstore in the chart's values means this chart stands on its own; while a breaking change, I think that's pretty valuable to get new people to use the chart. This gets people to MVP with the least amount of configuration possible (all they should need is a configuration for storage) - if they want all the bells and whistles (from what I can read, HA/scalability improvements?), they can continue forward from something that already works.

What are your ideas on this?

**Comment by chris-barbour-as** [comment]
I'm interested in switching to memberlist as well.

But is it supported by this helm chart? From my understanding, port 7946 needs to be open on the pods, and a headless service needs to be available for discovery.

**Comment by SudoBrendan** [comment]
It is supported. I used their [acceptance test (?)](https://github.com/cortexproject/cortex-helm-chart/blob/master/ci/test-values.yaml) as a guide.

**Comment by ShuzZzle** [comment]
This is now super easy to use with the 0.5.0 of the helm-chart. However we should add some more documentation
