### ISSUE TITLE
Nginx to display menu under the default ("/") endpoint

### ISSUE THREAD

**Issue by shybbko** [cortexproject/cortex-helm-chart#129]
Currently the nginx pod only shows some diagnostic info endpoints (ie. /ring) when directly visiting the /ring endpoint. What that means basically is that one needs to check ie. nginx config to see the list of endpoints available before being able to visit any of them. Any chance of nginx displaying a sort of menu under the default ("/") endpoint in a similar manner that the regular Cortex service does? See attached screenshot below:

![image](https://user-images.githubusercontent.com/49549423/109301587-76b4e380-7838-11eb-8967-4a746199e070.png)

**Comment by apmartins85** [comment]
+ Fix nginx paths. ie:
https://cortexmetrics.io/docs/api/#ingesters-ring-status 
vs.
https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/nginx-config.yaml#L47
