### ISSUE TITLE
Not clear what needs to change to deploy on GKE+BigTable

### ISSUE THREAD

**Issue by wy100101** [cortexproject/cortex-helm-chart#14]
I've been looking for some sort of direction for running cortex on GKE with bigtable as a backend store, and I just can't find anything.  Since I couldn't find anything in the documentation, I was hoping that the Helm chart might have the dials I needed to turn, but I don't see them here either.

How hard would it be to get the helm chart to support GKE+Helm?

**Comment by gramidt** [comment]
Hi @wy100101!

Unfortunately, this Helm chart was initially developed for just AWS; however, I'm currently working on updating it to Cortex 0.3.0 and refactoring it, so it can easily be used on GCP/GKE and AWS. This effort is being tracked in #8 and #6. The effort to add GKE and BigTable support should be easy once those enhancements are closed.

**Comment by weeco** [comment]
@wy100101 @gramidt Feel free to use https://github.com/cloudworkz/cortex-ops as inspiration. That repo has some additional information about how to run it on Gke with BigTable: https://github.com/cloudworkz/cortex-ops/tree/master/kubernetes#setup-on-gke--google-bigtable

**Comment by khaines** [comment]
I believe this issue can be closed now. With the latest helm chart the config is much more flexible to the other cloud providers.
