### ISSUE TITLE
Enable / Disable Security Context

### ISSUE THREAD

**Issue by 1995parham** [cortexproject/cortex-helm-chart#140]
I think it will be better if we can remove the security context from pods when we don't want them. if you agree I can do this with the following code snippet just like the Bitnami charts.

```
{{- if .Values.podSecurityContext.enabled }}
securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
{{- end }}
```

**Comment by ShuzZzle** [comment]
Yeah sure why not. Feel free to make an PR

**Comment by 1995parham** [comment]
There is another thing that I want to ask, what do you think about change helm files to have a non-root container. the main issue is the Nginx and if we replace it with the Bitnami Nginx we can support it I think.

**Comment by ShuzZzle** [comment]
> There is another thing that I want to ask, what do you think about change helm files to have a non-root container. the main issue is the Nginx and if we replace it with the Bitnami Nginx we can support it I think.

We will always look at PR's :)
