### ISSUE TITLE
Plans To Support Cortex v1.8+

### ISSUE THREAD

**Issue by Carmezim** [cortexproject/cortex-helm-chart#147]
Are there plans to release an updated chart adapted to the newer versions changes? 

v1.9 is in progress and seems to have lots of improvements from v1.7

**Comment by cabrinha** [comment]
Sounds like the project needs more support.

**Comment by cabrinha** [comment]
@Carmezim this is being tracked here: https://github.com/cortexproject/cortex-helm-chart/pull/154
