### ISSUE TITLE
Unable to upgrade cortex to 1.9

### ISSUE THREAD

**Issue by nh2121** [cortexproject/cortex-helm-chart#153]
When changing helm chart to image.tag: v1.9.0 the following errors occur:

` error loading config from /etc/cortex/cortex.yaml: Error parsing config file: yaml: unmarshal errors:                                                                                                                                                      │
│   line 49: field max_look_back_period not found in type chunk.StoreConfig                                                                                                                                                                                  │
│   line 71: field compress_responses not found in type frontend.CombinedFrontendConfig   `

**Comment by cabrinha** [comment]
Also:

```
line 105: field max_fetched_series_per_query not found in type validation.plain
```

**Comment by ShuzZzle** [comment]
Should be fixxed with #154. Closing for now...
