### ISSUE TITLE
SemVar isn't working in v1.18.9-eks-d1db3c

### ISSUE THREAD

**Issue by juan-ramirez-sp** [cortexproject/cortex-helm-chart#160]
https://github.com/cortexproject/cortex-helm-chart/blob/667c8785456b4a5b5494e96e4c95155e322c85d7/templates/nginx/nginx-ingress.yaml#L2

I'm deploying Cortex via Argo and I'm seeing weird behavior with how the ingress is handled. 

The packaged chart uses semverCompare to check the k8s API to determine what fields to include in the ingress. 

I recommend switching to checking the capabilities as I've seen no issues with that and I've seen other maintained charts use it.

EX: https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml

**Comment by ShuzZzle** [comment]
@juan-ramirez-sp 
In Version 0.5.0 we dropped support for k8 1.18, we don't aim to break older Clusters but we will not support it as the configuration becomes more and more cluttered

**Comment by ShuzZzle** [comment]
Ping @cabrinha

**Comment by cabrinha** [comment]
> @juan-ramirez-sp
> In Version 0.5.0 we dropped support for k8 1.18, we don't aim to break older Clusters but we will not support it as the configuration becomes more and more cluttered
> 
> > The packaged chart uses semverCompare to check the k8s API to determine what fields to include in the ingress.
> 
> Thats not really true anymore for 0.5.0 :D
> 
> But Its my opinion that we should only officially support the last 3 Kubernetes Versions.

I agree.
