### ISSUE TITLE
metric_relabel_configs in cortex-helm-chart

### ISSUE THREAD

**Issue by WilliamCassanova** [cortexproject/cortex-helm-chart#163]
I see that metric_relabel_configs is now supported in https://github.com/cortexproject/cortex/pull/3329.

Looking through the documentation is not readily apparent that the same support has been added to the cortex-helm-chart or am I overlooking something?

**Comment by ShuzZzle** [comment]
@WilliamCassanova thats correct. There are actually quite a few options missing from the included ServiceMonitors

**Comment by WilliamCassanova** [comment]
Thank You! I will give it a try.
