### ISSUE TITLE
Ingester Ingested Samples Rate is doubled after upgrading to Cortex-helm-chart 0.5.0

### ISSUE THREAD

**Issue by prprasad2020** [cortexproject/cortex-helm-chart#168]
I was using Cortex v1.7 and upgraded it to v1.9 yesterday. I used `cortex_distributor_received_samples_total` and `cortex_ingester_ingested_samples_total` to check distributor received rate and ingester ingested rate. And it was roughly same values when I'm running Cortex v1.7, but when I upgraded it to v1.9 `cortex_ingester_ingested_samples_total` metric value increased ~2.5x and `cortex_distributor_received_samples_total` value is staying same as before. I can see in-memory series(`cortex_ingester_memory_series`) in each ingester is also increased ~2.5x. Because of this ingester memory utilization is also higher than before. I have not increased the ingestion rate or did not configure new Prometheus remote writes, basically load is same as before. Anyone has any idea why this is happening ? 

I'm using below queries to get rates,
Distributor received samples rate : `sum(rate(cortex_distributor_received_samples_total[1m]))`
Ingester ingested samples rate : `sum(rate(cortex_ingester_ingested_samples_total[1m]))`

Below are the screenshots from Graphs before and after upgrade.

- Samples ingetion rates before,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/cc17615109e6bf7e3efa5317cb4b74fe90fa50c0/Cortex/Issue-4311/cortex-1.7.PNG?raw=true)

- Samples ingetion rates after,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/cc17615109e6bf7e3efa5317cb4b74fe90fa50c0/Cortex/Issue-4311/cortex-1.9.PNG?raw=true)

- In-memory series before,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/a53185724a7d510600e80d54efe69ae1d44d691e/Cortex/Issue-4311/cortex-1.7%20in-memory.PNG?raw=true)

- In-memory series after,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/cc17615109e6bf7e3efa5317cb4b74fe90fa50c0/Cortex/Issue-4311/cortex-1.9%20in-memory.PNG?raw=true)

**Comment by ShuzZzle** [comment]
Okay we definitely need to address this. Here are some quick thoughts of mine on how to solve that:

So basically whats causing is that, when using our ServiceMonitors you basically have the same target/endpoint twice for one job. This is because we sometimes have 2 Services [headless, non-headless] (while they do different things) also create each an endpoint for the pod. The result is this:
![image](https://user-images.githubusercontent.com/7032833/123065865-d5b5ee00-d40f-11eb-9f43-b075f69f8f28.png)

**Comment by prprasad2020** [comment]
I have another Cortex deployment with helm-chart 0.2.0 and Cortex v1.4. It has the same headless and non-headless services in Prometheus, but that cluster does not have this issue. Below is the screen shot of that,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/f134b9f6eb34ca62081d03558a2bea5ffb55d6b1/Cortex/Issue-4311/two%20services.png?raw=true)

Below are the metrics ingetion rates of that cluster,
![alt text](https://github.com/prprasad2020/Prasad-images/blob/5df64dd353bd7b362c2bd2e5b564d030ea733e53/Cortex/Issue-4311/cortex-1.4.PNG?raw=true)

Actually when I had Cortex v1.7 (helm-chart v0.4), headless and non-headless services were there but this issue was not there, I do not have screenshot of that since that deployment is not there.

**Comment by ShuzZzle** [comment]
I think I have found the Issue and will work on a fix

**Comment by ShuzZzle** [comment]
Hopefully fixxed in #169. If you deploy your own serviceMonitors then no guarantees but should be better

**Comment by ShuzZzle** [comment]
Underlying Issue was actually that the replication_factor changed from "1" -> "3". So can be closed!

**Comment by prprasad2020** [comment]
Thanks a lot @ShuzZzle
