### ISSUE TITLE
Cortex can read rules but doesn't activate them, All cortex rules are in inactive state while checking with API “/api/prom/api/v1/rules” in Ruler

### ISSUE THREAD

**Issue by Rahuly360** [cortexproject/cortex-helm-chart#178]
I install cortex 1.9.0 from GitHub as k8s deployment. All pods are in running. When I am loading rules in cortex ruler by API "/api/v1/rules/default" then rules are loading but their state is inactive. Ex: /api/v1/rules/default this API output rule is:
```JSON
{"name":"ruler_check_rules","file":"default","rules":[{"state":"inactive","name":"check_new_up","query":"up == 1","duration":0,"labels":{"cortex":"ruler"},"annotations":{"ruler":"cortex"},"alerts":[],"health":"ok","lastError":"","type":"alerting","lastEvaluation":"2021-07-20T07:57:53.002649507Z","evaluationTime":0.004718986}],"interval":60,"lastEvaluation":"2021-07-20T07:57:53.002626318Z","evaluationTime":0.004746094}
```
If anybody has any solution then please let me know the solution for it?

**Comment by ShuzZzle** [comment]
You might find more help in the cortex Slack channel

**Comment by Rahuly360** [comment]
Thank you @ShuzZzle I got the solution and successfully configure Ruler in Cortex and also ruler sending the alerts to Alertmanager.
