### ISSUE TITLE
ingress controller vs nginx

### ISSUE THREAD

**Issue by danfromtitan** [cortexproject/cortex-helm-chart#179]
The chart implementation around ingress-controller and nginx is confusing, looks like it cannot decide whether to use nginx with a load balancer in front or rather resort on [ingress-nginx](https://github.com/kubernetes/ingress-nginx) for requests intake to Cortex, as [seen here](https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/nginx/nginx-ingress.yaml#L1).

My point is if you want to use ingress-nginx (thus create an Ingress object), the nginx is part of that external chart, there is no need to deploy your own.

Reason for opening this issue is I need clarification for the direction you're taking this. For the time being I can disable both ingress and nginx in the chart and configure ingress-nginx from a wrapper, but I'd like to know whether you're going to be using ingress-nginx as a gateway or you plan to do something else.

**Comment by junkiebev** [comment]
You read my mind @danfromtitan

**Comment by ShuzZzle** [comment]
Yeah I can see why that is confusing. Currently the ingress Objects points to the provided nginx server. We are happy to discuss changes

**Comment by danfromtitan** [comment]
There are a number of pros & cons with ingress-nginx integration in Cortex helm chart, IMO the benefits are greater than the setbacks. That is unless you'd want to come-up with your proprietary gateway solution without re-inventing ingress-nginx :)

On the good side:
- it provides the meaning to solve the [tenant authorization story](https://cortexmetrics.io/docs/guides/auth/) in Cortex. To be honest the X-Scope-OrgID header is just a way to separate tenants, it doesn't provide any access control once the tenant name is known.
- you get a fully-baked gateway solution that comes with features that Cortex would need when it's exposed outside cluster local. I'm thinking here security (server & client TLS) as well as scalability (all nginx config knobs are already exposed).
- having an ingress resource allows further integration with other tools like external-dns or with cloud-provider specific implementations (i.e. load balancers, firewalls)
- as far as Cortex helm chart is concerned, you don't have to worry about ingress and nginx implementation details. All that's needed in Cortex chart is to declare a dependency and provide an ingress-nginx section in the values file. 

On the downside:
- deploying ingress-nginx from Cortex chart means it will end-up [in the same namespace](https://github.com/helm/helm/issues/5358). That makes a Cortex dedicated nginx instance, which is not ideal if you have other application in the same cluster that would need an Ingress. Typically I would want to have one ingress-nginx per cluster in a separate namespace and leverage the Ingress resource for a Cortex server section. But then you end-up with a half-baked solution, pretty much like it is now.
- ingress-nginx gets more complicated with every release. Giving away your own nginx implementation means you'd now have to put up with the [often convoluted ways](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/) ingress-nginx configures it.

**Comment by ShuzZzle** [comment]
> deploying ingress-nginx from Cortex chart means it will end-up in the same namespace. That makes a Cortex dedicated nginx instance, which is not ideal if you have other application in the same cluster that would need an Ingress. Typically I would want to have one ingress-nginx per cluster in a separate namespace and leverage the Ingress resource for a Cortex server section. But then you end-up with a half-baked solution, pretty much like it is now.

Yeah I don't really like that approach either. Preferably this helm-chart is about cortex and just cortex, I dont think it should provide a full-stack and come with everything. People should choose their own ingress controller, whether that be ingress-nginx or traefik or whatever. However I don't think that will work, because some settings we would have to set are very controller specific (headers, proxy stuff). We could just leave it generic and have it configureable, but that would only make the deployment harder for the enduser.

> ingress-nginx gets more complicated with every release. Giving away your own nginx implementation means you'd now have to put up with the often convoluted ways ingress-nginx configures it.

See above, yeah I really don't want the helm-chart to come with ingress-nginx controller. Honestly that really sounds like a bad idea.

**Comment by danfromtitan** [comment]
> Preferably this helm-chart is about cortex and just cortex, I dont think it should provide a full-stack and come with everything.

I agree, that's why I'm on the fence with the idea. It was much easier for me to disable ingress and nginx from this chart and deploy my own ingress-nginx with all the bells and whistles I wanted. The only use I've made of nginx in this chart was to find out the location URLs needed in lack of documentation.
