### ISSUE TITLE
Service monitor to nginx

### ISSUE THREAD

**Issue by apmartins85** [cortexproject/cortex-helm-chart#214]
Should we have a service monitor to gather metrics from Nginx (cortex-nginx)?

If not, feel free to close this issue!

**Comment by ShuzZzle** [comment]
I don't think nginx has built-in metrics. You would probably have to use something like this: https://github.com/nginxinc/nginx-prometheus-exporter

However as we use nginx only as an "example" (many people use different ways to publish cortex to the internet) I think this feature request would be out of scope

**Comment by apmartins85** [comment]
I agree with the exporter, and understand that the issue can be closed.
