### ISSUE TITLE
Update chart to cortex 1.0.0, k8s 1.16 apis

### ISSUE THREAD

**Issue by previ** [cortexproject/cortex-helm-chart#22]
I forked this chart and prepared an [updated chart](https://github.com/previ/cortex-helm-chart) compatible with cortex v1.0.0 and k8s 1.16, I am using it to deploy cortex with cassandra and azure blob storage backend, it should work also on aws (dynamodb and/or s3). 
If interested, I can submit a pull request.

**Comment by gramidt** [comment]
Happy Friday, @previ!

I apologize for the delayed response. I would absolutely love for you to submit the PR!

**Comment by previ** [comment]
Good! The pr is there: https://github.com/cortexproject/cortex-helm-chart/pull/25

**Comment by hairyhenderson** [comment]
@previ Since #25 is merged, this issue can be closed, right?

**Comment by previ** [comment]
Yes, sure! Closing it.
