### ISSUE TITLE
Cortex installation in custom namespace other than "cortex" is not working

### ISSUE THREAD

**Issue by kriskrishna** [cortexproject/cortex-helm-chart#225]

**Comment by ShuzZzle** [comment]
@kriskrishna Could you please provide additional Information? What is not working?

**Comment by kriskrishna** [comment]
I get this error in storage-gateway pod. I am using blocked storage using s3 on AWS.

level=warn ts=2021-09-20T22:10:11.368823431Z caller=bucket_stores.go:147 msg="failed to synchronize TSDB blocks" err="Access Denied"
level=info ts=2021-09-20T22:10:11.368940984Z caller=basic_lifecycler.go:197 msg="ring lifecycler is shutting down" ring=store-gateway
level=error ts=2021-09-20T22:10:11.369023709Z caller=client.go:234 msg="error getting path" key=collectors/store-gateway err="Get "http://consul-server:8500/v1/kv/collectors/store-gateway?index=142&stale=&wait=10000ms\": context canceled"
level=info ts=2021-09-20T22:10:11.371840626Z caller=basic_lifecycler.go:363 msg="unregistering instance from ring" ring=store-gateway
level=info ts=2021-09-20T22:10:11.374520989Z caller=basic_lifecycler.go:234 msg="instance removed from the ring" ring=store-gateway
level=error ts=2021-09-20T22:10:11.37460811Z caller=cortex.go:426 msg="module failed" module=store-gateway err="invalid service state: Failed, expected: Running, failure: initial blocks synchronization: Access Denied"
level=info ts=2021-09-20T22:10:11.374665349Z caller=module_service.go:91 msg="module stopped" module=memberlist-kv
level=info ts=2021-09-20T22:10:11.375837693Z caller=server_service.go:50 msg="server stopped"
level=info ts=2021-09-20T22:10:11.375852835Z caller=module_service.go:91 msg="module stopped" module=server
level=info ts=2021-09-20T22:10:11.375862498Z caller=cortex.go:415 msg="Cortex stopped"
level=error ts=2021-09-20T22:10:11.375905864Z caller=log.go:106 msg="error running cortex" err="failed services\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/__w/cortex/cortex/pkg/cortex/cortex.go:461\nmain.main\n\t/__w/cortex/cortex/cmd/cortex/main.go:190\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"

**Comment by ShuzZzle** [comment]
this is not helm-chart related. your dns is broken most likely. Ask in the slack for further help

**Comment by kriskrishna** [comment]
It works fine I choose "cortex" as namespace

**Comment by ShuzZzle** [comment]
> It works fine I choose "cortex" as namespace

Probably related to your DNS ("http://consul-server:8500/v1/kv/collectors/store-gateway?index=142&stale=&wait=10000ms\") this requires everything to be deployed in the same namespace otherwise you need to define the full dns name. As we do not deploy dns nor your consul configuration, this has nothing to do with our helm-chart. By the way my helmchart is running in a different namespace

**Comment by kriskrishna** [comment]
I am installing consul & cortex in the same custom namespace all the time.

**Comment by kriskrishna** [comment]
How about this warning: level=warn ts=2021-09-20T22:10:11.368823431Z caller=bucket_stores.go:147 msg="failed to synchronize TSDB blocks" err="Access Denied"
