### ISSUE TITLE
Support for cortex 1.10

### ISSUE THREAD

**Issue by eddycharly** [cortexproject/cortex-helm-chart#226]
Shouldn't cortex 1.10 be the most recent version deployed through the chart ?

**Comment by ShuzZzle** [comment]
It is (not released yet) but i just realised that https://github.com/cortexproject/cortex-helm-chart/blob/master/Chart.yaml#L3 shows v1.9.0 (but we don't use that)

**Comment by ShuzZzle** [comment]
See: https://github.com/cortexproject/cortex-helm-chart/pull/204

**Comment by eddycharly** [comment]
I'm not sure, the latest release is `0.6.0` and it deploys cortex `1.9.0`. #204 was merged but no release was generated ?

**Comment by eddycharly** [comment]
>  i just realised that https://github.com/cortexproject/cortex-helm-chart/blob/master/Chart.yaml#L3 shows v1.9.0 (but we don't use that)
you're right, maybe you should take the image version from `.Chart.AppVersion` (while still allowing to override it in the values) to be sure that `appVersion` is consistent with the deployment ?

**Comment by ShuzZzle** [comment]
> > i just realised that https://github.com/cortexproject/cortex-helm-chart/blob/master/Chart.yaml#L3 shows v1.9.0 (but we don't use that)
> 
> you're right, maybe you should take the image version from `.Chart.AppVersion` (while still allowing to override it in the values) to be sure that `appVersion` is consistent with the deployment ?

yep i will be doing that. You can sneak-peek for the upcoming 1.0.0 release in my personal branch

**Comment by ShuzZzle** [comment]
> I'm not sure, the latest release is `0.6.0` and it deploys cortex `1.9.0`. #204 was merged but no release was generated ?

Yep see my answer above :)
