### ISSUE TITLE
Release current master as 0.7.0 before 1.0.0

### ISSUE THREAD

**Issue by lahsivjar** [cortexproject/cortex-helm-chart#234]
@ShuzZzle Let me know if I can help in any way for the release.

**Comment by ShuzZzle** [comment]
Hey @lahsivjar 

Can you tell us one more time what exactly you are you trying to do?

**Comment by lahsivjar** [comment]
We need the [liveliness probe configuration for Memcache exporter released in bitnami chart version 5.15.1](https://github.com/bitnami/charts/pull/7421). Currently due to the lack of this when memcache is on high load and exporter cannot create a connection then it makes the pod unavailable due to hardcoded liveliness probe configuration in older version of helm chart.

**Comment by ShuzZzle** [comment]
> We need the [liveliness probe configuration for Memcache exporter released in bitnami chart version 5.15.1](https://github.com/bitnami/charts/pull/7421). Currently due to the lack of this when memcache is on high load and exporter cannot create a connection then it makes the pod unavailable due to hardcoded liveliness probe configuration in older version of helm chart.

Well... shouldn't be super long until 1.0.0. At least I don't know what might still be missing. I will talk with Tom later on about releasing it today/tomorrow. In the meantime can you deploy the chart from the master @lahsivjar ?

**Comment by lahsivjar** [comment]
Cool, makes sense. If the release ETA is within this week it works for us. If it takes longer I will deploy the chart. Closing this issue then.
