### ISSUE TITLE
Ingester lifecycle preStop shouldn't be specified in the default values file

### ISSUE THREAD

**Issue by lahsivjar** [cortexproject/cortex-helm-chart#239]
Calling ingester shutdown endpoint before terminating in case of rolling restart is unwanted in most cases and for big ingesters it increases rollout times. Since the value is specified in the default values.yaml file, overriding it via another values file is tricky since helm would merge the objects.

See:
https://github.com/helm/helm/issues/6465
https://github.com/helm/helm/issues/7902
https://github.com/helm/helm/issues/5407

Only way would be to use `--set`. The default values shouldn't specify the lifecycle and it should be upto the end-users to add it if they need it.

**Comment by ShuzZzle** [comment]
I can see how that would be annoying for development but why would you want to rolling restart all your ingesters?

**Comment by lahsivjar** [comment]
1. Updating cortex version
2. Changing ingester configurations (this is not that frequent however, we are in the process of tweaking some configurations on our prod workload)
3. Any change on configuration file currently retriggers rolling restart of ingesters

**Comment by ShuzZzle** [comment]
> Updating cortex version

Literally happens every couple of months. Why would somebody not do this "properly".

> Changing ingester configurations (this is not that frequent however, we are in the process of tweaking some configurations on our prod workload)
Any change on configuration file currently retriggers rolling restart of ingesters

For development ok sounds annoying but have you tried nulling the keys? I know helm is a bit buggy like this unfortunately

**Comment by lahsivjar** [comment]
> Literally happens every couple of months. Why would somebody not do this "properly".
I don't understand what "properly" means, normal restarts don't need to flush data to long-term storage, and using the shutdown endpoint is only necessary when doing a scaledown. Additionally, calling shutdown for every ingester not only increases unexpected IO to long-term storage, in case of block storage, it will cause missed queries works on a periodic scanning of storage buckets. I don't see how this is the proper way to do rollouts and why preStop lifecycle is required.

> For development ok sounds annoying but have you tried nulling the keys? I know helm is a bit buggy like this unfortunately
As I mentioned above, I don't understand why calling shutdown should be a required step and should be called on every termination irrespective of it being a dev env or a prod env. Additionally, scaledown in most cases should be more infrequent than updates.

Also, the [docs for the shutdown API](https://cortexmetrics.io/docs/api/#shutdown) mention it as an important part of scale down automation and not something to be done on every SIGTERM. It might be required by some deployments where scale down is frequently done but I don't see why it needs to be as a default value.

**Comment by ShuzZzle** [comment]
> > Literally happens every couple of months. Why would somebody not do this "properly".
> 
> I don't understand what "properly" means, normal restarts don't need to flush data to long-term storage, and using the shutdown endpoint is only necessary when doing a scaledown. Additionally, calling shutdown for every ingester not only increases unexpected IO to long-term storage, in case of block storage, it will cause missed queries since block storage works on a periodic scanning of storage buckets. I don't see how this is the proper way to do rollouts and why preStop lifecycle is required.
> 
> > For development ok sounds annoying but have you tried nulling the keys? I know helm is a bit buggy like this unfortunately
> 
> As I mentioned above, I don't understand why calling shutdown should be a required step and should be called on every termination irrespective of it being a dev env or a prod env.
> 
> Also, the [docs for the shutdown API](https://cortexmetrics.io/docs/api/#shutdown) mention it as an important part of scale down automation and not something to be done on every SIGTERM. It might be required by some deployments where scale down is frequently done but I don't see why it needs to be as a default value. Scaledown in most cases should be more infrequent than updates.

Sorry I mispoked. I can see how flushing the ingester in a restart scenario with `-querier.query-store-after` set to non-zero will lead to some problems. Theoretically and practically this needs to be set back to 0 or atleast lower when doing a "proper" scale-down. I can see how this PR to introduce graceful shutdown was maybe a bit rushed.

I'm cool with your PR if we provide a proper Wiki page here: https://cortexproject.github.io/cortex-helm-chart/ on how to scale-down the right way.
