### ISSUE TITLE
How do we test the installation on the cluster once we deploy the helm chart? 

### ISSUE THREAD

**Issue by nikhil-nomula** [cortexproject/cortex-helm-chart#248]
I deployed the helm chart on a K8s cluster. I see the pods are up and running successfully. How would I access cortex once it is deployed? 

I get a 404 not found after deploying. The pods come up just fine and are in running status 

```
kubectl --namespace cortex port-forward service/cortex-nginx 8080:80

curl http://127.0.0.1:8080/api/prom

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.3</center>
</body>
</html>
```

**Comment by ShuzZzle** [comment]
Hi,

You can see the paths here: https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/nginx/nginx-config.yaml

For example
- /healthz
- /ring
- /all_user_stats
- /api/prom/push
- etc.

**Comment by nikhil-nomula** [comment]
@ShuzZzle can you please invite me to the slack channel with this email nnomula@finishline.com?

**Comment by ShuzZzle** [comment]
> @ShuzZzle can you please invite me to the slack channel with this email [nnomula@finishline.com](mailto:nnomula@finishline.com)?

No, I can't its a public space. You can invite yourself. Check: https://events.linuxfoundation.org/archive/2020/kubecon-cloudnativecon-europe/attend/slack-guidelines/

**Comment by nikhil-nomula** [comment]
Got it, thank you @ShuzZzle !
