### ISSUE TITLE
cortex-store-gateway crash

### ISSUE THREAD

**Issue by Tasmana-banana** [cortexproject/cortex-helm-chart#250]
- level=info ts=2021-11-08T11:04:44.177273292Z caller=main.go:187 msg="Starting Cortex" version="(version=1.6.0, branch=HEAD, revision=2f7d37d)"
- level=info ts=2021-11-08T11:04:44.181844247Z caller=server.go:229 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
- level=info ts=2021-11-08T11:04:44.188375542Z caller=inmemory.go:172 msg="created in-memory index cache" maxItemSizeBytes=134217728 maxSizeBytes=1073741824 maxItems=maxInt
- level=info ts=2021-11-08T11:04:44.18916203Z caller=module_service.go:58 msg=initialising module=memberlist-kv
- level=info ts=2021-11-08T11:04:44.189379602Z caller=module_service.go:58 msg=initialising module=runtime-config
- level=info ts=2021-11-08T11:04:44.189377432Z caller=module_service.go:58 msg=initialising module=server
- level=info ts=2021-11-08T11:04:44.189934958Z caller=module_service.go:58 msg=initialising module=store-gateway
- level=info ts=2021-11-08T11:04:44.194744506Z caller=basic_lifecycler.go:252 msg="instance not found in the ring" instance=cortex-store-gateway-0 ring=store-gateway
- level=info ts=2021-11-08T11:04:44.194825757Z caller=basic_lifecycler_delegates.go:62 msg="not loading tokens from file, tokens file path is empty"
- level=info ts=2021-11-08T11:04:44.249957604Z caller=gateway.go:229 msg="waiting until store-gateway is JOINING in the ring"
- level=info ts=2021-11-08T11:04:45.482600679Z caller=gateway.go:233 msg="store-gateway is JOINING in the ring"
- level=info ts=2021-11-08T11:04:45.48267885Z caller=bucket_stores.go:123 msg="synchronizing TSDB blocks for all users"
- level=warn ts=2021-11-08T11:04:45.728623136Z caller=bucket_stores.go:128 msg="failed to synchronize TSDB blocks" err="Access Denied"
- level=error ts=2021-11-08T11:04:45.728747647Z caller=client.go:212 msg="error while rate-limiting" key=collectors/store-gateway err="context canceled"
- level=info ts=2021-11-08T11:04:45.728836648Z caller=basic_lifecycler.go:197 msg="ring lifecycler is shutting down" ring=store-gateway
- level=info ts=2021-11-08T11:04:45.762796585Z caller=basic_lifecycler.go:363 msg="unregistering instance from ring" ring=store-gateway
- level=info ts=2021-11-08T11:04:45.857012582Z caller=basic_lifecycler.go:234 msg="instance removed from the ring" ring=store-gateway
- level=error ts=2021-11-08T11:04:45.857127463Z caller=cortex.go:391 msg="module failed" module=store-gateway err="invalid service state: Failed, expected: Running, failure: initial blocks synchronization: Access Denied"
- level=info ts=2021-11-08T11:04:45.857226914Z caller=module_service.go:90 msg="module stopped" module=runtime-config
- level=info ts=2021-11-08T11:04:45.857272034Z caller=module_service.go:90 msg="module stopped" module=memberlist-kv
- level=info ts=2021-11-08T11:04:45.857375265Z caller=server_service.go:50 msg="server stopped"
- level=info ts=2021-11-08T11:04:45.857395586Z caller=module_service.go:90 msg="module stopped" module=server
- level=info ts=2021-11-08T11:04:45.857420376Z caller=cortex.go:380 msg="Cortex stopped"
- level=error ts=2021-11-08T11:04:45.857501017Z caller=log.go:150 msg="error running cortex" err="failed services\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/__w/cortex/cortex/pkg/cortex/cortex.go:426\nmain.main\n\t/__w/cortex/cortex/cmd/cortex/main.go:189\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"

I using this manifest as base https://gist.github.com/iamabhishek-dubey/ff6d49fc3d0bfda81d1f29e3869d522f 
The consul got up, s3 created and registered the keys for access, but the construction of the goethevey did not rise. Can someone point in which direction to look?

**Comment by Tasmana-banana** [comment]
This was IAM role

**Comment by ShuzZzle** [comment]
Figured was gonna suggest that this is not an helm-chart issue ^^. Glad you found the problem yourself
