### ISSUE TITLE
Support separate service accounts for each cortex service

### ISSUE THREAD

**Issue by jmcarp** [cortexproject/cortex-helm-chart#251]
I'm looking into using [gke workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) to assign gcp iam permissions to k8s pods, and I would like to be able to configure different service accounts per cortex service. For example, nginx doesn't need access to gcs, so ideally I'd use a different service account for nginx than for the ingesters.

Would you be open to a patch allowing users to override service account names by service? Happy to submit something if so.

**Comment by ShuzZzle** [comment]
Yep we are always open to any new ideas
