### ISSUE TITLE
Confused about prometheus remote_write

### ISSUE THREAD

**Issue by ahsan-n** [cortexproject/cortex-helm-chart#253]
Hi, trying to deploy cortex helm chart one part is to add remote write in prometheus config. If I understood correctly I have to add cortex ingester point to push. So I aded this in prometheus config:

```
server:
  remoteWrite:
  - url: http://cortex-ingester.cortex.svc.cluster.local:8080/api/prom/push
```

from prometheus getting these logs:
```
ts=2021-11-12T07:02:33.126Z caller=dedupe.go:112 component=remote level=error remote_name=176c69 url=http://cortex-ingester.cortex.svc.cluster.local:8080/api/prom/push msg="non-recoverable error" count=47 err="server returned HTTP status 404 Not Found: 404 page not found"
ts=2021-11-12T07:02:33.138Z caller=dedupe.go:112 component=remote level=error remote_name=176c69 url=http://cortex-ingester.cortex.svc.cluster.local:8080/api/prom/push msg="non-recoverable error" count=56 err="server returned HTTP status 404 Not Found: 404 page not found"
ts=2021-11-12T07:02:33.140Z caller=dedupe.go:112 component=remote level=error remote_name=176c69 url=http://cortex-ingester.cortex.svc.cluster.local:8080/api/prom/push msg="non-recoverable error" count=54 err="server returned HTTP status 404 Not Found: 404 page not found"
```
not sure what i might be doing wrong.

**Comment by ShuzZzle** [comment]
Hey,

you have that wrong. You want to write to the distributor service. The path should be
```
/api/prom/push
```
given the default configuration for the legacy API. Check here for futher details: https://cortexmetrics.io/docs/api/#remote-write

Remote Write
> http://cortex-distributor.cortex.svc.cluster.local:8080/api/prom/push

Read for Grafana
> http://cortex-query-frontend.cortex.svc.cluster.local:8080/api/prom

**Comment by ahsan-n** [comment]
Thanks @ShuzZzle  🙇 
this worked
