### ISSUE TITLE
configs necessary for unified alerting in grafana v8 missing

### ISSUE THREAD

**Issue by shamsalmon** [cortexproject/cortex-helm-chart#257]
Hello everyone,

In case anyone received an error in grafana where it shows [404 not found] in the alerting config, you should add the following to your helm chart config. I am not sure if this should be added to the helm chart, as I have no doubt grafana will change this datasource to do things less strangely. These can be passed through the serverSnippets in the nginx config.

```
    nginx:
      enabled: true
      replicas: 1
      config:
        serverSnippet: |
          # Config Config
          location ~ /api/prom/rules {
            proxy_pass      http://cortex-ruler.operations.svc.cluster.local:8080$request_uri;
          }

          location = /api/prom/api/v1/alerts {
            proxy_pass      http://cortex-alertmanager.operations.svc.cluster.local:8080/api/v1/alerts;
          }

```

**Comment by ShuzZzle** [comment]
Interesting... will check. Thanks!

**Comment by ShuzZzle** [comment]
thank you for raising this issue. You were absolutely right.

I feel like there should be atleast some documentation or maybe we should consider reworking all the rules in the nginx pod

**Comment by shamsalmon** [comment]
> thank you for raising this issue. You were absolutely right.
> 
> I feel like there should be atleast some documentation or maybe we should consider reworking all the rules in the nginx pod

I think rule rework probably makes sense. I am not sure what *exactly* grafana expects to be there but at minimum adding these two rules at least seems to fix the issue. I haven't done extensive testing quite yet but it works well enough to add alerts for us now.

**Comment by ginoledesma** [comment]
I ran into this when I deployed Cortex v1.10-rc1 a few months back. I've attached a snippet of my rendered nginx config file generated from v0.6.0 of the helm chart's template:

```
http {
  default_type application/octet-stream;
  client_max_body_size 1M;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" $http_x_scope_orgid';
  access_log   /dev/stderr  main  if=$logging;
  sendfile     on;
  tcp_nopush   on;
  resolver kube-dns.kube-system.svc.cluster.local;

  # FIXME: find a better way of dealing with Grafana 8.1's unified alerting feature
  # Use the X-AM-Client header to let us know that it's grafana that we're dealing with.
  # Grafana expects to pull the AlertManager YAML config using the same endpoint as
  # the list of active alerts
  map $http_x_am_client $cortex_alert_backend {
    default "http://fleet-local-cortex-ruler.cortex.svc.cluster.local:8080/api/prom/api/v1/alerts";
    grafana "http://fleet-local-cortex-alertmanager.cortex.svc.cluster.local:8080/api/v1/alerts";
  }

  server { # simple reverse-proxy
    listen 80;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    proxy_http_version 1.1;

    location = /healthz {
      return 200 'alive';
    }

    # Distributor Config
    location = /ring {
      proxy_pass      http://fleet-local-cortex-distributor.cortex.svc.cluster.local:8080$request_uri;
    }

    location = /all_user_stats {
      proxy_pass      http://fleet-local-cortex-distributor.cortex.svc.cluster.local:8080$request_uri;
    }

    location = /api/prom/push {
      proxy_pass      http://fleet-local-cortex-distributor.cortex.svc.cluster.local:8080$request_uri;
    }

    ## New Remote write API. Ref: https://cortexmetrics.io/docs/api/#remote-write
    location = /api/v1/push {
      proxy_pass      http://fleet-local-cortex-distributor.cortex.svc.cluster.local:8080$request_uri;
    }


    # Alertmanager Config
    location ~ /api/prom/alertmanager/.* {
      proxy_pass      http://fleet-local-cortex-alertmanager.cortex.svc.cluster.local:8080$request_uri;
    }

    # This returns the AlertManager configuration in YAML, not the list of active alerts
    location ~ ^/api/v1/alerts {
      proxy_pass      http://fleet-local-cortex-alertmanager.cortex.svc.cluster.local:8080$request_uri;
    }

    location ~ /multitenant_alertmanager/status {
      proxy_pass      http://fleet-local-cortex-alertmanager.cortex.svc.cluster.local:8080$request_uri;
    }

    # Ruler Config
    location ~ /api/v1/rules {
      proxy_pass      http://fleet-local-cortex-ruler.cortex.svc.cluster.local:8080$request_uri;
    }

    location ~ /ruler/ring {
      proxy_pass      http://fleet-local-cortex-ruler.cortex.svc.cluster.local:8080$request_uri;
    }

    # Config Config
    location ~ /api/prom/configs/.* {
      proxy_pass      http://fleet-local-cortex-configs.cortex.svc.cluster.local:8080$request_uri;
    }

    # NOTE: Grafana 8.1 Unified Alerting / next-generation alert
    # grafana makes certain assumptions using the base path /api/prom:
    #   what                  endpoint                               target       target_endpoint
    # - health-check          /api/prom/alertmanager/api/v2/status   alertmanager /api/prom/alertmanager/api/v2/status
    # - contact points        /api/prom/api/v1/alerts                alertmanager /api/v1/alerts
    # - notification policies /api/prom/api/v1/alerts                alertmanager /api/v1/alerts
    # - silences              /api/prom/alertmanager/api/v2/alets    alertmanager /api/prom/alertmanager/api/v2/alerts
    # - silences              /api/prom/alertmanager/api/v2/silences alertmanager /api/prom/alertmanager/api/v2/silences
    # - list alerts           /api/prom/api/v1/alerts                ruler        /api/prom/api/v1/alerts
    # - list rules            /api/prom/api/v1/rules                 ruler        /api/prom/api/v1/rules
    # - alert rules           /api/prom/rules                        ruler        /api/prom/rules
    # Herein lies the conflict with /api/prom/v1/alerts needing to be sent to either alertmanager or ruler

    location ~ /api/prom/rules {
      proxy_pass      http://fleet-local-cortex-ruler.cortex.svc.cluster.local:8080$request_uri;
    }

    location ~ ^/api/prom/api/v1/alerts {
      proxy_pass      $cortex_alert_backend;
    }

    location ~ ^/api/prom/api/v1/rules {
      proxy_pass      http://fleet-local-cortex-ruler.cortex.svc.cluster.local:8080$request_uri;
    }

    # Query Config
    location ~ /api/prom/.* {
      proxy_pass      http://fleet-local-cortex-query-frontend.cortex.svc.cluster.local:8080$request_uri;
    }

    ## New Query frontend APIs as per https://cortexmetrics.io/docs/api/#querier--query-frontend
    location ~ ^/prometheus/api/v1/(read|metadata|labels|series|query_range|query) {
      proxy_pass      http://fleet-local-cortex-query-frontend.cortex.svc.cluster.local:8080$request_uri;
    }

    location ~ /prometheus/api/v1/label/.* {
      proxy_pass      http://fleet-local-cortex-query-frontend.cortex.svc.cluster.local:8080$request_uri;
    }

  }
}
```

**Comment by ShuzZzle** [comment]
Hey @ginoledesma,

Thanks for the tip with `X-AM-Client`. I couldn't find any documentation on this. Have yo u concluded this yourself or is there some documentation I'm unaware off? I tried grabbing through grafana/grafana source but couldn't find any `X-AM-Client` header or is this just GEM thing?

**Comment by ShuzZzle** [comment]
Ping @ginoledesma

**Comment by engrkenjitanaka** [comment]
@ShuzZzle have you tried it with Grafana 8.3.4? Can't seem to make it work

**Comment by ShuzZzle** [comment]
> @ShuzZzle have you tried it with Grafana 8.3.4? Can't seem to make it work

No I have not tried with that specific version but I believe with 8.3.x. To troubleshoot it you should check nginx pod logs and the http log from grafana.

Make sure that you have added the 2 endpoints from this Issue to the nginx pod!

**Comment by engrkenjitanaka** [comment]
> > @ShuzZzle have you tried it with Grafana 8.3.4? Can't seem to make it work
> 
> No I have not tried with that specific version but I believe with 8.3.x. To troubleshoot it you should check nginx pod logs and the http log from grafana.
> 
> Make sure that you have added the 2 endpoints from this Issue to the nginx pod!

`Failed to load rules config from Cortex: 404 from rules config endpoint. Perhaps ruler API is not enabled?`
Turns out to be a problem in 8.3.4

**Comment by ShuzZzle** [comment]
> > > @ShuzZzle have you tried it with Grafana 8.3.4? Can't seem to make it work
> > 
> > No I have not tried with that specific version but I believe with 8.3.x. To troubleshoot it you should check nginx pod logs and the http log from grafana.
> > 
> > Make sure that you have added the 2 endpoints from this Issue to the nginx pod!
> 
> `Failed to load rules config from Cortex: 404 from rules config endpoint. Perhaps ruler API is not enabled?`
> Turns out to be a problem in 8.3.4

Have you confirmed that by using an older version or is this just an assumption

**Comment by engrkenjitanaka** [comment]
> > > > @ShuzZzle have you tried it with Grafana 8.3.4? Can't seem to make it work
> > > 
> > > 
> > > No I have not tried with that specific version but I believe with 8.3.x. To troubleshoot it you should check nginx pod logs and the http log from grafana.
> > > Make sure that you have added the 2 endpoints from this Issue to the nginx pod!
> > 
> > 
> > `Failed to load rules config from Cortex: 404 from rules config endpoint. Perhaps ruler API is not enabled?`
> > Turns out to be a problem in 8.3.4
> 
> Have you confirmed that by using an older version or is this just an assumption

I'm assuming this is a bug on 8.3.4 (Or maybe something changed with Grafana again?) as it worked fine when I downgraded to 8.3.3
