### ISSUE TITLE
Compactor: Documentation vs. Helm Chart inconsistency

### ISSUE THREAD

**Issue by morsik** [cortexproject/cortex-helm-chart#260]
Documentation (https://cortexmetrics.io/docs/blocks-storage/compactor/) says:

> The compactor is **stateless**.

But Helm Chart installs Compactor as StatefulSet (https://github.com/cortexproject/cortex-helm-chart/tree/master/templates/compactor).

This seems like mistake in documentation or this Helm Chart. What is actual state of Compactor?

**Comment by ShuzZzle** [comment]
It's definitely stateless. I don't know how it behaves in case of a crash but should definitely be a Deployment

**Comment by morsik** [comment]
Ok, so the only potential reason to have it as StatefulSet is to provide separated PVs to multiple Pods probably…

If I understand correctly (just assuming now): Compactor downloads chunks from S3 bucket, reorganizes them into larger pieces and uploads again to S3? And PV is needed just as this temporary storage?

Or there is something more to this story?

**Comment by ShuzZzle** [comment]
that's correct, but storage can be just of type `emptyDir: {}`. No reason for pv/pvc since it's only cached

**Comment by ShuzZzle** [comment]
@kd7lxl What's your take on this? Sounds like a good idea to get this in for the upcoming 1.0.0 Release

- Change sts to deployment
- Change PV to emptyDir for /data (where blocks will be cached)

**Comment by kd7lxl** [comment]
One feature of StatefulSet is that pods are created with deterministic names, not random. This might affect how a compactor rejoins the ring after a rollout. I'm not familiar enough with the compactor sharding behavior to know if this brings any advantage.

**Comment by morsik** [comment]
Distributor and Ingester are also using rings, but they are standard Deployments as I can see.

But disclaimer: I'm using Cortex for about 6 hours, so I may not know many things yet :D

**Comment by ShuzZzle** [comment]
> Distributor and Ingester are also using rings, but they are standard Deployments as I can see.
> 
> But disclaimer: I'm using Cortex for about 6 hours, so I may not know many things yet :D

You have the option to also choose sts for the Ingester which i do **recommend**. The Distributor is just a deployment.

> One feature of StatefulSet is that pods are created with deterministic names, not random. This might affect how a compactor rejoins the ring after a rollout. I'm not familiar enough with the compactor sharding behavior to know if this brings any advantage.

I don't think it matters but I can test that

**Comment by morsik** [comment]
> You have the option to also choose sts for the Ingester which i do recommend

@ShuzZzle is there some place in documentation regarding Kubernetes and why there are such recomendations (and for what use cases)? I didn't see any yet.

And if they can be Deployment or StatefulSet depending on options, maybe the same could be done with Compactor? I'm also wondering the same for Store Gateway as it contains just indexes from S3, so… maybe it could be "stateless" too since it contains just cache of S3?

**Comment by ShuzZzle** [comment]
> > You have the option to also choose sts for the Ingester which i do recommend
> 
> @ShuzZzle is there some place in documentation regarding Kubernetes and why there are such recomendations (and for what use cases)? I didn't see any yet.

That's just personal preference. If you deploy your Ingesters with a `Deployment` then you rely on the cortex replication_factor to make sure that you do not loose any data in case of a crash. With the STS option each Ingester gets his own PV.

> And if they can be Deployment or StatefulSet depending on options, maybe the same could be done with Compactor?

As far as I can tell there is no real benefit (to be tested) of having the compactor with its own PV. Therefore I would not offer that option.

> I'm also wondering the same for Store Gateway as it contains just indexes from S3, so… maybe it could be "stateless" too since it contains just cache of S3?

The Store gateway is **semi-stateful**. While you technically can run it as a deployment, there are definitely some benefits to reap (like storing index-headers to avoid frequent downloads). This is also the recommend way of deploying the store-gateway in the cortex documentation

**Comment by morsik** [comment]
Thanks for explanation!

**Comment by ShuzZzle** [comment]
Alright had a talk with some of the cortex guys and somebody pointed out that the compactor for large clusters might need huge amounts of storage, therefore we will keep the STS in order to stop polluting the local-disk.

This also gets worse since compactor sharding is done by tenants so large tenants will only be one compactor at a time. (parallel compaction not done yet)

**Comment by morsik** [comment]
Thanks for explanation!

So I assume, if I run only 1 tenant, I don't need more than 1 compactor?

**Comment by ShuzZzle** [comment]
> Thanks for explanation!
> 
> So I assume, if I run only 1 tenant, I don't need more than 1 compactor?

Correct, but please feel free to confirm this. Should be easily done with cpu metrics from cAdvisor something like that :)
