### ISSUE TITLE
Reconcile kvstore recommendations

### ISSUE THREAD

**Issue by jmcarp** [cortexproject/cortex-helm-chart#262]
I noticed that the [readme](https://github.com/cortexproject/cortex-helm-chart#key-value-store) and [docs](https://github.com/cortexproject/cortex-helm-chart/blob/898ec7dc5c8dd92c24c12247c7049d7dc28b2b10/docs/guides/memberlist.markdown) both recommend using memberlist as the kvstore, but the chart defaults in values.yaml use consul. I would expect the recommendations and the defaults to match. Should we change values.yaml to default to memberlist?

**Comment by jmcarp** [comment]
Oh, I see this is getting addressed in #227. Nice!

**Comment by ShuzZzle** [comment]
Yep :) <3
