### ISSUE TITLE
Do not log 200/202 in nginx

### ISSUE THREAD

**Issue by fculpo** [cortexproject/cortex-helm-chart#281]
Hi,

It would be a good idea not to log all the 200 and 202 request reaching nginx, this is generating quite a lot of logs.

We could add this part in the nginx config map

```
map $status $loggable {
  ~^[23]  0;
  default 1;
}

access_log   /dev/stderr  main if=$loggable;
```

**Comment by ShuzZzle** [comment]
Fine with me, if we can make it a bit more flexible and configurable?

**Comment by kd7lxl** [comment]
This configuration is already possible by overriding `.nginx.config.mainSnippet`, right? Can you try that and report back? You might consider authoring a [guide](https://github.com/cortexproject/cortex-helm-chart/tree/master/docs/guides) to show operators how to do this themselves.

**Comment by ShuzZzle** [comment]
Closing due to @kd7lxl comment. Should be already possible
