### ISSUE TITLE
hpas always show out of sync in ArgoCD

### ISSUE THREAD

**Issue by moustafab** [cortexproject/cortex-helm-chart#284]
ArgoCD and gitops controllers when rendering and comparing the HorizontalPodAutoscalers are always out of sync because the HPA controller always reorders `spec.metrics` to have memory before cpu. I believe this is due to precedence, but here are the relevant issues:

https://github.com/argoproj/argo-cd/issues/1079
https://github.com/kubernetes/kubernetes/issues/74099

I suggest, for ease of use, reordering all the `spec.metrics` to have `memory` first and `cpu` second.

**Comment by ShuzZzle** [comment]
I don't see why we should do it. Do you wanna have a go at it?

**Comment by kd7lxl** [comment]
This sucks, but it looks like the easiest resolution is just to reorder it in our chart.
