### ISSUE TITLE
How to implement metrics & visualize in Grafana without Promethues, Only using Cortex?

### ISSUE THREAD

**Issue by harshasrimal** [cortexproject/cortex-helm-chart#292]
Currently we implemented metrics with Prometheus, Cortex and Grafana in a kubernetes environment. We have visualized metrics in Grafana using Prometheus data-source by using cortex-query-frontend-headless service. We have integrated Cortex in the Prometheus helm chart by using a remote_write url

   ```
 remote_write:
       url: http://cortex.cortex/api/prom/push
```

Is there any way to visualize metrics in Grafana for a sample application without using Prometheus, only using Cortex? If No why Prometheus is required? ,If Yes please mention  a document,

**Comment by ShuzZzle** [comment]
It's not entirely to me clear what you want, but you don't have to use Prometheus for sending metrics to Cortex. If you want to visualize Cortex metrics within Grafana then you would need a second Prometheus running in your cortex cluster

**Comment by harshasrimal** [comment]
Thank you @ShuzZzle for you quick response. How can i send metrics directly to cortex without using Prometheus? If we can send metrics without Prometheus why we need second Prometheus to visualize in Grafana?

**Comment by ShuzZzle** [comment]
> Thank you @ShuzZzle for you quick response. How can i send metrics directly to cortex without using Prometheus? If we can send metrics without Prometheus why we need second Prometheus to visualize in Grafana? 

You can use everything that supports the Prometheus remote write format. Grafana Agent or vmagent from victoriametrics. Quite a few out there.

You will need a 2nd Prometheus just for the # cortex_ metrics from the cortex applications, because Cortex simply can't scrape itself. That's why all the components in this helm chart have Servicemonitors

**Comment by ShuzZzle** [comment]
I see that you also asked in the CNCF slack. You are better off there, I will close this here👍
