### ISSUE TITLE
Nginx cache permission error

### ISSUE THREAD

**Issue by huuzing** [cortexproject/cortex-helm-chart#294]
Hi,

I tried to deploy Cortex in our K8 cluster. But when I look into the Nginx pod it gives me the following error:

`2021/12/24 10:12:32 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)`

This causes the pod to go into the CrashLoopBackOff status.

Can anyone please let me know what is going wrong?

Hope to hear from you soon.

**Comment by huuzing** [comment]
In addition:

I have been using the general Values.yml with the addition of the dnsResolver to the right resolver.

**Comment by ShuzZzle** [comment]
https://hub.docker.com/_/nginx

See: "Running nginx as a non-root user". I don't know your config but If I were to guess then it's probably that

**Comment by huuzing** [comment]
Hi @ShuzZzle 

Thanks for the reply.

I use the default config which is generated by de helm chart. I only changed the resolve attribute to our dns resolver.

I will look into it as non-root, since it will be deployed eventually to a non-root environment.

I will let you know.

**Comment by ShuzZzle** [comment]
I thought you already tried to run nginx as non root using the securityContext. Can you please share your relevant config? I personally don't have that Issue

**Comment by huuzing** [comment]
@ShuzZzle 

This is my nginx config from the configmap:

`kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    meta.helm.sh/release-name: cortex
    meta.helm.sh/release-namespace: cortex
  selfLink: /api/v1/namespaces/cortex/configmaps/cortex-nginx
  resourceVersion: '362677575'
  name: cortex-nginx
  uid: 271afd0f-0bab-4ace-bc49-cf0136b79a91
  creationTimestamp: '2021-12-27T14:53:25Z'
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2021-12-27T14:53:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:nginx.conf': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
            'f:helm.sh/chart': {}
  namespace: cortex
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: cortex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cortex
    app.kubernetes.io/version: v1.10.0
    helm.sh/chart: cortex-1.1.0
data:
  nginx.conf: |-
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      default_type application/octet-stream;
      client_max_body_size 1M;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for" $http_x_scope_orgid';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver dns-default.openshift-dns.svc.cluster.local;

      server { # simple reverse-proxy
        listen 80;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        proxy_http_version 1.1;

        

        location = /healthz {
          # auth_basic off is not set here, even when a basic auth directive is
          # included in the server block, as Nginx's NGX_HTTP_REWRITE_PHASE
          # (point when this return statement is evaluated) comes before the
          # NGX_HTTP_ACCESS_PHASE (point when basic auth is evaluated). Thus,
          # this return statement returns a response before basic auth is
          # evaluated.
          return 200 'alive';
        }

        # Distributor Config
        location = /ring {
          proxy_pass      http://cortex-distributor.cortex.svc.<domain>:8080$request_uri;
        }

        location = /all_user_stats {
          proxy_pass      http://cortex-distributor.cortex.svc.<domain>:8080$request_uri;
        }

        location = /api/prom/push {
          proxy_pass      http://cortex-distributor.cortex.svc.<domain>:8080$request_uri;
        }

        ## New Remote write API. Ref: https://cortexmetrics.io/docs/api/#remote-write
        location = /api/v1/push {
          proxy_pass      http://cortex-distributor.cortex.svc.<domain>:8080$request_uri;
        }

        # Alertmanager Config
        location ~ /api/prom/alertmanager/.* {
          proxy_pass      http://cortex-alertmanager.cortex.svc.<domain>:8080$request_uri;
        }

        location ~ /api/v1/alerts {
          proxy_pass      http://cortex-alertmanager.cortex.svc.<domain>:8080$request_uri;
        }

        location ~ /multitenant_alertmanager/status {
          proxy_pass      http://cortex-alertmanager.cortex.svc.<domain>:8080$request_uri;
        }

        # Ruler Config
        location ~ /api/v1/rules {
          proxy_pass      http://cortex-ruler.cortex.svc.<domain>:8080$request_uri;
        }

        location ~ /ruler/ring {
          proxy_pass      http://cortex-ruler.cortex.svc.<domain>:8080$request_uri;
        }

        # Config Config
        location ~ /api/prom/configs/.* {
          proxy_pass      http://cortex-configs.cortex.svc.<domain>:8080$request_uri;
        }

        # Query Config
        location ~ /api/prom/.* {
          proxy_pass      http://cortex-query-frontend.cortex.svc.<domain>:8080$request_uri;
        }

        ## New Query frontend APIs as per https://cortexmetrics.io/docs/api/#querier--query-frontend
        location ~ ^/prometheus/api/v1/(read|metadata|labels|series|query_range|query) {
          proxy_pass      http://cortex-query-frontend.cortex.svc.<domain>:8080$request_uri;
        }

        location ~ /prometheus/api/v1/label/.* {
          proxy_pass      http://cortex-query-frontend.cortex.svc.<domain>:8080$request_uri;
        }
      }
    }`

**Comment by ShuzZzle** [comment]
Sorry I meant the helm values for the nginx section. The yaml override for the helm chart

**Comment by huuzing** [comment]
@ShuzZzle 

Sorry for the late reaction, here is the nginx config.

`nginx:
  enabled: true
  replicas: 2
  http_listen_port: 80
  config:
    dnsResolver: dns-default.openshift-dns.svc.cluster.local
    # -- ref: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
    client_max_body_size: 1M
    # -- arbitrary snippet to inject in the http { } section of the nginx config
    httpSnippet: ""
    # -- arbitrary snippet to inject in the top section of the nginx config
    mainSnippet: ""
    # -- arbitrary snippet to inject in the server { } section of the nginx config
    serverSnippet: ""
    setHeaders: {}
    # -- (optional) List of [auth tenants](https://cortexmetrics.io/docs/guides/auth/) to set in the nginx config
    auth_orgs: []
    # -- (optional) Name of basic auth secret.
    # In order to use this option, a secret with htpasswd formatted contents at
    # the key ".htpasswd" must exist. For example:
    #
    #   apiVersion: v1
    #   kind: Secret
    #   metadata:
    #     name: my-secret
    #     namespace: <same as cortex installation>
    #   stringData:
    #     .htpasswd: |
    #       user1:$apr1$/woC1jnP$KAh0SsVn5qeSMjTtn0E9Q0
    #       user2:$apr1$QdR8fNLT$vbCEEzDj7LyqCMyNpSoBh/
    #
    # Please note that the use of basic auth will not identify organizations
    # the way X-Scope-OrgID does. Thus, the use of basic auth alone will not
    # prevent one tenant from viewing the metrics of another. To ensure tenants
    # are scoped appropriately, explicitly set the `X-Scope-OrgID` header
    # in the nginx config. Example
    #   setHeaders:
    #     X-Scope-OrgID: $remote_user
    basicAuthSecretName: ""

  image:
    repository: nginx
    tag: 1.21
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    annotations: {}
    labels: {}

  serviceAccount:
    # -- "" disables the individual serviceAccount and uses the global serviceAccount for that component
    name: ""

  resources: {}

  # -- Additional Cortex container arguments, e.g. log.level (debug, info, warn, error)
  extraArgs: {}

  # -- Pod Labels
  podLabels: {}

  # -- Pod Annotations
  podAnnotations: {}

  nodeSelector: {}
  affinity: {}
  annotations: {}
  persistentVolume:
    subPath:

  startupProbe:
    httpGet:
      path: /healthz
      port: http-metrics
    failureThreshold: 10
  livenessProbe:
    httpGet:
      path: /healthz
      port: http-metrics
  readinessProbe:
    httpGet:
      path: /healthz
      port: http-metrics

  securityContext: {}

  containerSecurityContext:
    enabled: true
    readOnlyRootFilesystem: false

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  terminationGracePeriodSeconds: 10

  tolerations: []

  podDisruptionBudget:
    maxUnavailable: 1

  initContainers: []
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  extraPorts: []
  env: []

  autoscaling:
    # -- Creates a HorizontalPodAutoscaler for the nginx pods.
    enabled: false
    minReplicas: 2
    maxReplicas: 30
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 0  # 80
    # -- Ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior
    behavior: {}`

**Comment by ShuzZzle** [comment]
> @ShuzZzle
> 
> Sorry for the late reaction, here is the nginx config.
> 
> `nginx: enabled: true replicas: 2 http_listen_port: 80 config: dnsResolver: dns-default.openshift-dns.svc.cluster.local # -- ref: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size client_max_body_size: 1M # -- arbitrary snippet to inject in the http { } section of the nginx config httpSnippet: "" # -- arbitrary snippet to inject in the top section of the nginx config mainSnippet: "" # -- arbitrary snippet to inject in the server { } section of the nginx config serverSnippet: "" setHeaders: {} # -- (optional) List of [auth tenants](https://cortexmetrics.io/docs/guides/auth/) to set in the nginx config auth_orgs: [] # -- (optional) Name of basic auth secret. # In order to use this option, a secret with htpasswd formatted contents at # the key ".htpasswd" must exist. For example: # # apiVersion: v1 # kind: Secret # metadata: # name: my-secret # namespace: <same as cortex installation> # stringData: # .htpasswd: | # user1:$apr1$/woC1jnP$KAh0SsVn5qeSMjTtn0E9Q0 # user2:$apr1$QdR8fNLT$vbCEEzDj7LyqCMyNpSoBh/ # # Please note that the use of basic auth will not identify organizations # the way X-Scope-OrgID does. Thus, the use of basic auth alone will not # prevent one tenant from viewing the metrics of another. To ensure tenants # are scoped appropriately, explicitly set the `X-Scope-OrgID` header # in the nginx config. Example # setHeaders: # X-Scope-OrgID: $remote_user basicAuthSecretName: ""
> 
> image: repository: nginx tag: 1.21 pullPolicy: IfNotPresent
> 
> service: type: ClusterIP annotations: {} labels: {}
> 
> serviceAccount: # -- "" disables the individual serviceAccount and uses the global serviceAccount for that component name: ""
> 
> resources: {}
> 
> # -- Additional Cortex container arguments, e.g. log.level (debug, info, warn, error)
> extraArgs: {}
> 
> # -- Pod Labels
> podLabels: {}
> 
> # -- Pod Annotations
> podAnnotations: {}
> 
> nodeSelector: {} affinity: {} annotations: {} persistentVolume: subPath:
> 
> startupProbe: httpGet: path: /healthz port: http-metrics failureThreshold: 10 livenessProbe: httpGet: path: /healthz port: http-metrics readinessProbe: httpGet: path: /healthz port: http-metrics
> 
> securityContext: {}
> 
> containerSecurityContext: enabled: true readOnlyRootFilesystem: false
> 
> strategy: type: RollingUpdate rollingUpdate: maxSurge: 0 maxUnavailable: 1
> 
> terminationGracePeriodSeconds: 10
> 
> tolerations: []
> 
> podDisruptionBudget: maxUnavailable: 1
> 
> initContainers: [] extraContainers: [] extraVolumes: [] extraVolumeMounts: [] extraPorts: [] env: []
> 
> autoscaling: # -- Creates a HorizontalPodAutoscaler for the nginx pods. enabled: false minReplicas: 2 maxReplicas: 30 targetCPUUtilizationPercentage: 80 targetMemoryUtilizationPercentage: 0 # 80 # -- Ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior behavior: {}`

Sorry bud but I refuse to look through this mess. Can you please format your post?

**Comment by huuzing** [comment]
Hi @ShuzZzle  & @thibautcharry

I have fixed it by using the image from https://hub.docker.com/r/nginxinc/nginx-unprivileged.

We are indeed using non-root environments. So I had to use the unprivileged image.

Thank for taking the time to look into this issue.

I will close this issue.
