### ISSUE TITLE
distributor_config: shard_by_all_labels true when default is false

### ISSUE THREAD

**Issue by mweibel** [cortexproject/cortex-helm-chart#298]
hi,

going over the helm chart values yaml I noticed it sets [`distributor.shard_by_all_labels: true`](https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L106) while the [default configuration in cortex config](https://cortexmetrics.io/docs/configuration/configuration-file/#distributor_config) has it as default false. 

Is there a reason for that and should that maybe be changed to match the default of cortex config?

Cheers,
Michael

**Comment by ShuzZzle** [comment]
https://cortexmetrics.io/docs/configuration/arguments/#distributor

No specific reason but I think it might be a good Idea since...

> Warning: disabling this flag can lead to a much less balanced distribution of load among the ingesters.

**Comment by mweibel** [comment]
I see, thanks for the link. 

For context: I'm quite new to cortex and trying to configure it correctly for our use case. I noticed this difference in configuration setting because I was investigating the amount of network traffic we have on our cortex cluster. I disabled it to see what the impact would be. My current guess is that setting this to true has higher traffic (and more costs if multiple zones and a cloud provider which bills inter-zone traffic) but on the other hand ensures a more stable system. 

Question is, I guess: what do the default helm chart values say. Are these recommended for production values or are these just important settings one might need to adjust, but leaving them to the default?

**Comment by ShuzZzle** [comment]
> I see, thanks for the link.
> 
> For context: I'm quite new to cortex and trying to configure it correctly for our use case. I noticed this difference in configuration setting because I was investigating the amount of network traffic we have on our cortex cluster. I disabled it to see what the impact would be. My current guess is that setting this to true has higher traffic (and more costs if multiple zones and a cloud provider which bills inter-zone traffic) but on the other hand ensures a more stable system.
> 
> Question is, I guess: what do the default helm chart values say. Are these recommended for production values or are these just important settings one might need to adjust, but leaving them to the default?

Yeah those are best-effort-ish values for production. Often times the cortex default are super generic and really just are some starting point. Doesn't mean those values fit in every environment/deployment. I'm afraid everybody has to fine-tune cortex to their specific use-case

**Comment by mweibel** [comment]
sure, makes sense. Thanks for your replies - closing this.
