### ISSUE TITLE
Possible not have alertmanager config hardcoded into nginx.conf

### ISSUE THREAD

**Issue by WilliamCassanova** [cortexproject/cortex-helm-chart#325]
We want to set https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L162 to false and set https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L1060 to true.

But because of hard-coded valuess in https://github.com/cortexproject/cortex-helm-chart/blob/ad2f5cf3ce961af813fc73b9530be75a585322ac/templates/nginx/nginx-config.yaml#L88-L103 this doesn't seem possible.  

Is there some other way of doing this that anyone knows of?

**Comment by nschad** [comment]
Is it not possible because the endpoints in nginx config would lead to nothing? What exactly is your problem?

**Comment by WilliamCassanova** [comment]
OK.  The problem we are seeing is:
```
2022/02/28 17:19:06 [emerg] 1#1: host not found in upstream "cortex-alertmanager.cortex.svc.cluster.local" in /etc/nginx/nginx.conf:72
nginx: [emerg] host not found in upstream "cortex-alertmanager.cortex.svc.cluster.local" in /etc/nginx/nginx.conf:72
```

**Comment by nschad** [comment]
> OK.  The problem we are seeing is:
> ```
> 2022/02/28 17:19:06 [emerg] 1#1: host not found in upstream "cortex-alertmanager.cortex.svc.cluster.local" in /etc/nginx/nginx.conf:72
> nginx: [emerg] host not found in upstream "cortex-alertmanager.cortex.svc.cluster.local" in /etc/nginx/nginx.conf:72
> ```

Yeah this is to be expected. Feel free to address the Issue and create an PR.

**Comment by WilliamCassanova** [comment]
I will give it a try on my local computer....Once I have confidence my fix works I will push a PR.

**Comment by nschad** [comment]
> I will give it a try on my local computer....Once I have confidence my fix works I will push a PR.

Basically you would have to group every component endpoint and wrap them in an if clause, should be pretty straight forward :)

**Comment by WilliamCassanova** [comment]
OK.  I believe I have a fix.  Having never pushed to this repo I assume the general work-flow you guys follow is:
1. Create a branch off of `Master`.
2. Make the changes needed.
3. `git commit` those changes.
4. `git push` 
5. Create a PR.

At this point I don't have write permissions or am I going about this in the wrong way?
