### ISSUE TITLE
Add support for topology spread constraints

### ISSUE THREAD

**Issue by Tristan971** [cortexproject/cortex-helm-chart#335]
[Topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) is just about the only way to force the scheduler to ~~keep its opinions to itself~~ respect the anti-affinities one might want, even if it means being unable to schedule a pod altogether.

It'd be great to have support for in the chart for it...

The reason in this case is [this policy of kubernetes-sigs/descheduler](https://github.com/kubernetes-sigs/descheduler#removeduplicates) constantly evicting one of my ingester pods who got scheduled on the same node as another, and the scheduler constantly instantly rescheduling it on the same exact node hereafter.

I'm happy to do a PR with the changes needed if no one objects to this.

I'd propose to keep it empty by default, so it'd be a pure opt-in. One could consider giving a preset one but those tend to be flaky depending on the labels people might be using on their nodes etc, so I'm not sure it wouldn't end up needing to be almost free-form anyway.

**Comment by nschad** [comment]
Yep feel free to create an PR as an opt-in feature. 

> I'd propose to keep it empty by default, so it'd be a pure opt-in. One could consider giving a preset one but those tend to be flaky depending on the labels people might be using on their nodes etc, so I'm not sure it wouldn't end up needing to be almost free-form anyway.

I agree with you here. I don't think a preset would work really well.
