### ISSUE TITLE
Cortex does not get deployed 1.3.0 vesion

### ISSUE THREAD

**Issue by kadursandy** [cortexproject/cortex-helm-chart#349]
Cortex is not getting deployed on in OKE Cluster(in Oracle Cloud Infra). We use 3 worker nodes with ARM based architecture.

K8S Cluster Version "v1.22.5"
Helm Chart "1.3.0"
Cortex Version: v1.11.0

The prerequisites are taken care before helm install.
All the pods are going to Crashloopbackoff state afte helm install with custom values.

1. Is Cortex architecture dependant? Does it support x86 arch only?
2.  Does is support arm64 arch/processor on worker nodes?
3. if support for arm64 is not there, then when will the support come in . Please let me know. OCI OKE clusters support both arm64 and x86_64 based processors on worker(compute) nodes.

**Comment by nschad** [comment]
> Cortex is not getting deployed on in OKE Cluster(in Oracle Cloud Infra). We use 3 worker nodes with ARM based architecture.
> 
> K8S Cluster Version "v1.22.5"
> Helm Chart "1.3.0"
> Cortex Version: v1.11.0
> 
> The prerequisites are taken care before helm install.
> All the pods are going to Crashloopbackoff state afte helm install with custom values.
> 
> 1. Is Cortex architecture dependant? Does it support x86 arch only?
> 2.  Does is support arm64 arch/processor on worker nodes?
> 3. if support for arm64 is not there, then when will the support come in . Please let me know. OCI OKE clusters support both arm64 and x86_64 based processors on worker(compute) nodes.
> 
> 
> 

Wrong repository please head over to the slack or cortexproject/cortex repo.
