### ISSUE TITLE
Cortex get lots of error every 2 hours

### ISSUE THREAD

**Issue by sockyone** [cortexproject/cortex-helm-chart#358]
We are monitoring our error code return from Cortex. We realize that every 2 hours, error rate is very high and delayed our data. I don't think this is because of remoteWrite protocol. Is it Cortex job or something?
![image](https://user-images.githubusercontent.com/35925547/170403741-05ad4c24-1bf3-413f-bd0c-37b1bd801f78.png)

**Comment by nschad** [comment]
This repository is about the cortex-helm-chart not cortex itself. Please ask in the #cortex CNCF provided slack channel or headover to cortexproject/cortex.
