### ISSUE TITLE
Alert manager not work

### ISSUE THREAD

**Issue by sockyone** [cortexproject/cortex-helm-chart#361]
We got this in Ruler logs:
`http://cortex-alertmanager.cortex.svc.cluster.local:8080/api/prom/alertmanager/api/v1/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"`
I already set up alert manager config for tenant digilife.prod. But it won't help. 
![image](https://user-images.githubusercontent.com/35925547/170646155-8b635f4b-3b1c-4100-b015-da2915d3c8f7.png)

**Comment by nschad** [comment]
See: https://github.com/cortexproject/cortex-helm-chart/issues/358#issuecomment-1138918315
