### ISSUE TITLE
Static port for cortex-nginx service

### ISSUE THREAD

**Issue by crisschomar** [cortexproject/cortex-helm-chart#372]
I want to register Cortex(cortex-nginx service especially) in my own service discovery. The problem is that everytime I reinstall Cortex, cortex-nginx NodePort is changing. 
Correct me if Im wrong, but shouldn`t this chart give us possibility to define static NodePort for the cortex-nginx service?

**Comment by nschad** [comment]
> I want to register Cortex(cortex-nginx service especially) in my own service discovery. The problem is that everytime I reinstall Cortex, cortex-nginx NodePort is changing. Correct me if Im wrong, but shouldn`t this chart give us possibility to define static NodePort for the cortex-nginx service?

yep feel free to create an PR which introduces this logic. Although I think it's weird to do anything Node Port related 🤷

**Comment by TaylorMutch** [comment]
> I want to register Cortex(cortex-nginx service especially) in my own service discovery. The problem is that everytime I reinstall Cortex, cortex-nginx NodePort is changing. Correct me if Im wrong, but shouldn`t this chart give us possibility to define static NodePort for the cortex-nginx service?

Its certainly possible to pin a static port, but it seems like you'd be better off specifying an ingress pointing to the service. Would have to know more about your use case, but this does seem kinda odd.
