### ISSUE TITLE
How to toggle cortex prometheus metrics

### ISSUE THREAD

**Issue by ahsan-n** [cortexproject/cortex-helm-chart#376]
Hi, we want to disable cortex metrics as we are not monitoring them over Grafana :) Any guide on how we can disable metrics from cortex helm chart?

**Comment by nschad** [comment]
> Hi, we want to disable cortex metrics as we are not monitoring them over Grafana :) Any guide on how we can disable metrics from cortex helm chart?

You want to disable the `/metrics` endpoint from the cortex components (ingester, distributor, querier... etc.)?

I think it's

```yaml
 # Register the intrumentation handlers (/metrics etc).
 # CLI flag: -server.register-instrumentation
[register_instrumentation: <boolean> | default = true]
```
