### ISSUE TITLE
error calling eq: missing argument for comparison

### ISSUE THREAD

**Issue by fxnn** [cortexproject/cortex-helm-chart#38]
Seems like 93baa61cb69 introduced syntax errors in Go template expressions.

When cloning the repo, then invoking

    $ helm dependency update
    $ helm install cortex --namespace cortex /path/to/working/copy

I receive the following output:

```
Error: template: cortex/templates/table-manager-dep.yaml:102:7: executing "cortex/templates/table-manager-dep.yaml" at <eq .Values.useExternalConfig>: error calling eq: missing argument for comparison
```

The named code location looks as follows:

```
{{- if eq .Values.useExternalConfig }}
            secretName: {{ .Values.externalConfigSecretName }}
{{- else }}
            secretName: {{ template "cortex.fullname" . }}
{{- end }}
```

According to [text/template documentation](https://golang.org/pkg/text/template/#:~:text=eq,arg2), `eq` does indeed expect a second argument, and I guess it should simply be `{{- if .Values.useExternalConfig }}`.

**Comment by Alon-Katz** [comment]
Hey, Did you manage to run this? because I have the same issue
