### ISSUE TITLE
Ingester's Horizontal Pod Autoscaler is configurable for memory only

### ISSUE THREAD

**Issue by shybbko** [cortexproject/cortex-helm-chart#384]
Cortex Ingester's HPA (https://github.com/cortexproject/cortex-helm-chart/blob/ad2f5cf3ce961af813fc73b9530be75a585322ac/templates/ingester/ingester-hpa.yaml) can be configured for memory only, but not CPU (missing `targetCPUUtilizationPercentage ` block). 

While the ingesters are generally memory-intensive pods, I think it would be nice to be able to scale if CPU usage is high.

So the question would be - is the design intentional?

**Comment by nschad** [comment]
yes that was intentional as CPU scaling for ingesters in my opinion is not really relevant.
