### ISSUE TITLE
Run rulers as a StatefulSet

### ISSUE THREAD

**Issue by disambiguationuk** [cortexproject/cortex-helm-chart#388]
We're using a sidecar to render and load rules for the ruler. On restart though the ruler would lose it's rules cache definitions until the sidecar grabs a new set of rules. Switching the rulers to run as a StatefulSet would mitigate this issue, are there any gotchas that mean we should run it as a Deployment rather than a StatefulSet?

**Comment by nschad** [comment]
> We're using a sidecar to render and load rules for the ruler. On restart though the ruler would lose it's rules cache definitions until the sidecar grabs a new set of rules. Switching the rulers to run as a StatefulSet would mitigate this issue, are there any gotchas that mean we should run it as a Deployment rather than a StatefulSet?

No I don't think so. You would have to switch from the default empityDir volumes too

**Comment by disambiguationuk** [comment]
Ok we've been doing a bit of work to get this to work with our custom sidecars, it's working but there's some fun with permissions in the default ```/data/rules``` path. Will open a PR when it's stable.
