### ISSUE TITLE
The upgrade-v1 guide contains a configuration error in the kvstore-mirror.yaml and kvstore-memberlist.yaml examples

### ISSUE THREAD

**Issue by wwalters12** [cortexproject/cortex-helm-chart#393]
When following the [upgrade-v1](https://github.com/cortexproject/cortex-helm-chart/blob/master/docs/guides/upgrade-v1.markdown) guide to migrate the keystore from consul to memberlist, the kvstore-mirror.yaml and kvstore-memberlist.yaml files contain the value `config.ingester.ring.kvstore: *kvstore`.  

I believe this is an error as the correct value is already present: `config.ingester.lifecycler.ring.kvstore: *kvstore`

When applying these values, multiple cortex services start crash looping trying to parse the invalid `ingester.ring` value.

**Comment by nschad** [comment]
thank you!
