### ISSUE TITLE
Help with consul configuration for cortex

### ISSUE THREAD

**Issue by Alon-Katz** [cortexproject/cortex-helm-chart#41]
Hey,

I managed to deploy cortex with consul to the kubernetes cluster. but the injesters are failing:

> consul-consul-js6d2                      1/1     Running            0          19m
> consul-consul-server-0                   1/1     Running            0          19m
> consul-consul-server-1                   1/1     Running            0          19m
> consul-consul-wcfgw                      1/1     Running            0          19m
> cortex-alertmanager-755c9b4b89-xcpcc     1/1     Running            0          18m
> cortex-configs-5d5697cd86-5f2kp          1/1     Running            0          18m
> cortex-distributor-59d79c45d-r6gbb       1/1     Running            0          18m
> cortex-distributor-59d79c45d-sxg7j       1/1     Running            0          18m
> cortex-ingester-5bddf84c86-5bvdq         0/1     CrashLoopBackOff   8          18m
> cortex-ingester-5bddf84c86-jm4pj         0/1     CrashLoopBackOff   8          18m
> cortex-ingester-5bddf84c86-wc66p         0/1     CrashLoopBackOff   8          18m
> cortex-nginx-7777b94c7c-dsk9s            1/1     Running            0          18m
> cortex-nginx-7777b94c7c-v6xvl            1/1     Running            0          18m
> cortex-querier-dbdc7877-djhfp            1/1     Running            0          18m
> cortex-querier-dbdc7877-qkt4n            1/1     Running            0          18m
> cortex-query-frontend-5b6d7458f6-ddqm9   1/1     Running            0          18m
> cortex-query-frontend-5b6d7458f6-m2qrl   1/1     Running            0          18m
> cortex-ruler-6d5d87967c-855kq            1/1     Running            0          18m
> cortex-table-manager-5dd895987c-6nsk7    1/1     Running            0          18m

**The injester logs are**:

> level=info ts=2020-08-19T08:08:48.086424152Z caller=server.go:179 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
> level=info ts=2020-08-19T08:08:48.109296185Z caller=main.go:119 msg="Starting Cortex" version="(version=1.1.0, branch=HEAD, revision=9db28c16)"
> level=info ts=2020-08-19T08:08:48.109674551Z caller=module_service.go:58 msg=initialising module=runtime-config
> level=info ts=2020-08-19T08:08:48.109713991Z caller=manager.go:109 msg="runtime config disabled: file not specified"
> level=info ts=2020-08-19T08:08:48.109789562Z caller=module_service.go:58 msg=initialising module=memberlist-kv
> level=info ts=2020-08-19T08:08:48.109892824Z caller=module_service.go:58 msg=initialising module=store
> level=info ts=2020-08-19T08:08:48.110027045Z caller=module_service.go:58 msg=initialising module=ingester
> level=info ts=2020-08-19T08:08:48.110459112Z caller=lifecycler.go:485 msg="not loading tokens from file, tokens file path is empty"
> level=info ts=2020-08-19T08:08:48.110722767Z caller=cortex.go:336 msg="Cortex started"
> level=error ts=2020-08-19T08:08:48.113373408Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.115753676Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.118156474Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.120795706Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.123158083Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.125487879Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.128252664Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.130838254Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.133505106Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=error ts=2020-08-19T08:08:48.135682611Z caller=client.go:131 msg="error getting key" key=collectors/ring err="Get http://consul:8500/v1/kv/collectors/ring?consistent=: dial tcp: lookup consul on 100.64.0.10:53: no such host"
> level=warn ts=2020-08-19T08:08:48.135900014Z caller=module_service.go:88 msg="module failed with error" module=ingester err="ingester subservice failed: service &{0xc00060b0e0 {{{consul collectors/ {{consul:8500  20000000000 true 1 1} {[] 10000000000 10} {  false 2000000000 0x29d3870} 0x29d5e80} <nil>} 60000000000 1} 512 5000000000 0 0 60000000000 [eth0 en0] 0    0 cortex-ingester-5bddf84c86-wc66p false 9095} 0xc000b1a000 {0xc0008abd00} 0xc00009de60 cortex-ingester-5bddf84c86-wc66p 100.123.71.104:9095 ingester ring  true {{0 0} 0 0 0 0} 2 [] {0 0} {13819107869685958768 85609582 0x564a1a0} false {{0 0} 0 0 0 0} 0} failed: failed to join the ring ingester: failed to CAS collectors/ring"
> level=error ts=2020-08-19T08:08:48.135959875Z caller=cortex.go:348 msg="module failed" module=ingester error="ingester subservice failed: service &{0xc00060b0e0 {{{consul collectors/ {{consul:8500  20000000000 true 1 1} {[] 10000000000 10} {  false 2000000000 0x29d3870} 0x29d5e80} <nil>} 60000000000 1} 512 5000000000 0 0 60000000000 [eth0 en0] 0    0 cortex-ingester-5bddf84c86-wc66p false 9095} 0xc000b1a000 {0xc0008abd00} 0xc00009de60 cortex-ingester-5bddf84c86-wc66p 100.123.71.104:9095 ingester ring  true {{0 0} 0 0 0 0} 2 [] {0 0} {13819107869685958768 85609582 0x564a1a0} false {{0 0} 0 0 0 0} 0} failed: failed to join the ring ingester: failed to CAS collectors/ring"
> level=info ts=2020-08-19T08:08:48.136058047Z caller=module_service.go:90 msg="module stopped" module=runtime-config
> level=info ts=2020-08-19T08:08:48.136096157Z caller=module_service.go:90 msg="module stopped" module=memberlist-kv
> level=info ts=2020-08-19T08:08:48.136140288Z caller=module_service.go:90 msg="module stopped" module=store
> level=info ts=2020-08-19T08:08:48.13625325Z caller=server_service.go:48 msg="server stopped"
> level=info ts=2020-08-19T08:08:48.136296721Z caller=cortex.go:337 msg="Cortex stopped"
> level=error ts=2020-08-19T08:08:48.136353082Z caller=log.go:140 msg="error running cortex" err="failed services\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:388\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:121\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"

Are there any changes that need to be made to the consul helm chart or the cortex helm chart to make it work?
Thanks !

**Comment by simonxmh** [comment]
your consul endpoint is probably unavailable because it's having troubles with the lookup. I think since you named your consul consul. You should configure the host to be consul-consul:8500

**Comment by robertwol** [comment]
Hi @Alon-Katz

**Comment by Alon-Katz** [comment]
Thanks! it helped. I will close the issue :)
