### ISSUE TITLE
cortex-store-gateway-0 stateful set always shows as starting and also restarting frequently 

### ISSUE THREAD

**Issue by lokeshr183** [cortexproject/cortex-helm-chart#464]
Labels: bug

I have  cortex running  with  v1.7.0 on EKS 1.23 version  and after applying  new AMI cortex-store-gateway-0  pod   is  unhealthy and not running  and also noticed  pod is restarting for every 30 minutes.

Below are the errors found:
**1) In the EKS cortex-store-gateway-0 pod below event is occurring very frequently** 

Startup probe failed: HTTP probe failed with statuscode: 503
Source:  kubelet ip-10-xxxxxx. compute.internal
Count: 103
Sub-object: spec.containers{store-gateway}

**2) Before pod get restarted can see below error**

023-05-30T20:34:39+05:30 level=info ts=2023-05-30T15:04:39.242512719Z caller=bucket.go:575 org_id=xxxx-services-xxx msg="loaded new block" elapsed=687.196926ms id=01GVT610VKBQCW23PYJY1K3B4G
2023-05-30T20:34:39+05:30 level=info ts=2023-05-30T15:04:39.250110177Z caller=module_service.go:96 msg="module stopped" module=memberlist-kv
2023-05-30T20:34:39+05:30 level=info ts=2023-05-30T15:04:39.252110232Z caller=server_service.go:50 msg="server stopped"
2023-05-30T20:34:39+05:30 level=info ts=2023-05-30T15:04:39.252596225Z caller=module_service.go:96 msg="module stopped" module=server
2023-05-30T20:34:39+05:30 level=info ts=2023-05-30T15:04:39.252617237Z caller=cortex.go:437 msg="Cortex stopped"
2023-05-30T20:34:39+05:30 level=error ts=2023-05-30T15:04:39.25399988Z caller=log.go:106 msg="error running cortex" err="failed services\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/__w/cortex/cortex/pkg/cortex/cortex.go:483\nmain.main\n\t/__w/cortex/cortex/cmd/cortex/main.go:195\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
Logs from 5/30/2023, 8:34:34 PM

**Below is the pod describe details:**
$ kubectl describe pod cortex-store-gateway-0 -n cortex
Name:             cortex-store-gateway-0
Namespace:        cortex
Priority:         0
Service Account:  cortex
Node:             ip-1xxxxxxxxx
Start Time:       Wed, 31 May 2023 05:43:45 -0600
Labels:           app.kubernetes.io/component=store-gateway
                  app.kubernetes.io/instance=cortex
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=cortex
                  app.kubernetes.io/part-of=memberlist
                  app.kubernetes.io/version=v1.13.0
                  controller-revision-hash=cortex-store-gateway-575664db74
                  helm.sh/chart=cortex-1.7.0
                  statefulset.kubernetes.io/pod-name=cortex-store-gateway-0
Annotations:      checksum/config: de4eeccfb0563d873a7110dbb88178d256f577e9acbc7174ddaae63a249d39b5
                  kubectl.kubernetes.io/restartedAt: 2023-05-30T13:04:07Z
                  kubernetes.io/psp: eks.privileged
                  prometheus.io/port: 8080
                  prometheus.io/scrape: true
Status:           Running
IP:               10.169.x.y
IPs:
  IP:           10.169.x.y
Controlled By:  StatefulSet/cortex-store-gateway
Containers:
  store-gateway:
    Container ID:  containerd://5077fec322fc4b9e8e29f69dc4e70a0c0569efe8746c35673204fcfebcd46a62
    Image:         quay.io/cortexproject/cortex:v1.13.0
    Image ID:      quay.io/cortexproject/cortex@sha256:ea54db771e4ba84beab0ec7fb9ef7e92c81fcce99c7abcf19e9055fd4438da14
    Ports:         8080/TCP, 9095/TCP, 7946/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      -target=store-gateway
      -config.file=/etc/cortex/cortex.yaml
      -blocks-storage.bucket-store.index-cache.backend=memcached
      -blocks-storage.bucket-store.index-cache.memcached.addresses=dns+cortex-memcached-blocks-index.cortex.svc.cluster.local:11211
      -blocks-storage.bucket-store.chunks-cache.backend=memcached
      -blocks-storage.bucket-store.chunks-cache.memcached.addresses=dns+cortex-memcached-blocks.cortex.svc.cluster.local:11211
      -blocks-storage.bucket-store.metadata-cache.backend=memcached
      -blocks-storage.bucket-store.metadata-cache.memcached.addresses=dns+cortex-memcached-blocks-metadata.cortex.svc.cluster.local:11211
    State:          Running
      Started:      Wed, 31 May 2023 06:17:14 -0600
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 31 May 2023 05:45:03 -0600
      Finished:     Wed, 31 May 2023 06:17:13 -0600
    Ready:          False
    Restart Count:  1
    Requests:
      cpu:        1
      memory:     8Gi
    Liveness:     http-get http://:http-metrics/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:http-metrics/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Startup:      http-get http://:http-metrics/ready delay=120s timeout=1s period=30s #success=1 #failure=60
    Environment:  <none>
    Mounts:
      /data from storage (rw)
      /etc/cortex from config (rw)
      /etc/cortex-runtime-config from runtime-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-t9jdt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  storage-cortex-store-gateway-0
    ReadOnly:   false
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cortex
    Optional:    false
  runtime-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cortex-runtime-config
    Optional:  false
  kube-api-access-t9jdt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  3m4s (x113 over 61m)  kubelet  Startup probe failed: HTTP probe failed with statuscode: 503

Any thoughts on this issue

**Comment by nschad** [comment]
Still relevant?
