### ISSUE TITLE
Do not set .spec.replicas for store-gateway if autoscaling is enabled

### ISSUE THREAD

**Issue by alex-berger** [cortexproject/cortex-helm-chart#472]
If a *HorizontalPodAutoscaler* (HPA) is in place, one **must not** explicitly set `.spec.replicas` on the corresponding workload (*StatefulSet* or *Deployment*). Failing to adhere to that rule can cause severe service outage as the workload is scaled down unexpectedly and then might crash as it immediately gets overloaded (RAM or CPU).

In https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/store-gateway/store-gateway-statefulset.yaml#L13 

```
  replicas: {{ .Values.store_gateway.replicas }}
```

should actually be:

```
  {{- if not .Values.store_gateway.autoscaling.enabled }}
  replicas: {{ .Values.store_gateway.replicas }}
  {{- end }}
```

**Comment by nschad** [comment]
Thanks.

Do you want to give it a go?

**Comment by husnialhamdani** [comment]
Hi @nschad,
 I Interested to work on it, can you please assign to me?
