### ISSUE TITLE
Chart.yaml on release 2.1.0 uses cortex v1.14.1, should use 1.15.3

### ISSUE THREAD

**Issue by webdz9r** [cortexproject/cortex-helm-chart#478]
Master branch [Chart.yaml ](https://github.com/cortexproject/cortex-helm-chart/blob/391f65e52fa22ed883d2d700463325354c773ba8/Chart.yaml#L3) uses Cortex 1.15.3 but the latest release 2.1.0 of the [chart.yaml](https://github.com/cortexproject/cortex-helm-chart/blob/ca2a4e8ec2c360a314f245de7e4052a90d93fb22/Chart.yaml#L3) still references 1.14.1

Can you please fix this so we don't have to patch our deployments, thanks also noted this with @friedrichg via slack

**Comment by nschad** [comment]
Yes we just need to cut a new release for that to happen. Unfortunately I don't have enough time at the moment

**Comment by webdz9r** [comment]
unacceptable - upgrading to this release completed broke our deployment. After patching post after `helm template` with the correct version our deployment was restored in working order.
