### ISSUE TITLE
Update helm chart to support cortex v1.17

### ISSUE THREAD

**Issue by theeYoshi** [cortexproject/cortex-helm-chart#498]
Cortex has been updated to v1.17 (currently 1.17.1) a few weeks ago and I'd like to request for an update in the helm chart so we can deploy the newest cortex version

**Comment by kd7lxl** [comment]
This would be a great first contribution if you would like to open a PR. Here's an example of the previous version bump PR: https://github.com/cortexproject/cortex-helm-chart/pull/489

**Comment by nschad** [comment]
Renovate seems to be dead :(

**Comment by kd7lxl** [comment]
I'm not sure where Renovate was running before. It's possible to run as a Github Actions workflow, but doesn't look it it was a workflow in this repo.

**Comment by nschad** [comment]
> I'm not sure where Renovate was running before. It's possible to run as a Github Actions workflow, but doesn't look it it was a workflow in this repo.

I think the app was enabled globally (for this org) or atleast for this repo. It definitely didn't run in any github actions context or hosted locally.
