### ISSUE TITLE
Using Cassandra as storage, how cortex helm template for ingester read cassandra configs for connection

### ISSUE THREAD

**Issue by techy16** [cortexproject/cortex-helm-chart#5]
Hi,

Can you please help how cortex helm template can be used for connecting to cassandra. I wanted to connect all the cortex components whichever needs a Cassandra connect to pull data or push data into cassandra.

**Comment by gramidt** [comment]
@techy16 - Unfortunately, the Helm chart does not currently support Cassandra; however, I would be more than happy to work with you on adding it.

**Comment by khaines** [comment]
(cleaning up older issues)

Utilizing Cassandra should now be possible with the config YAML support
