### ISSUE TITLE
err="Must set -dynamodb.url in aws mode\nerror creating index client"

### ISSUE THREAD

**Issue by TechHoops** [cortexproject/cortex-helm-chart#58]
I'm trying to install cortex with block storage and I'm getting the error below, please let me know what I'm doing wrong.  thanks

level=info ts=2020-10-07T04:51:48.651140802Z caller=server.go:179 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2020-10-07T04:51:48.651791474Z caller=log.go:140 msg="error initializing cortex" err="Must set -dynamodb.url in aws mode\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:153\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).initStore\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:288\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).initModuleServices\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:298\ngithub.com/cortexproject/cortex/pkg/cortex.New\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:237\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:116\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).initModuleServices\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:300\ngithub.com/cortexproject/cortex/pkg/cortex.New\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:237\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:116\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"

-- values-dev.yaml--
  storage:
    engine: chunks
    aws:
      s3: "https://cortext-storage.s3.amazonaws.com"
      bucketnames: "cortex-storage"

-- install command --
helm upgrade --install  cortex --namespace cortex eks/helm/clop/cortex --values eks/helm/clop/cortex/values-dev.yaml

**Comment by khaines** [comment]
in your values-dev.yaml file, your storage engine is set to chunks, not blocks. So you are also required to have an index database in that setup, which is why you are getting the dynamodb error. 

Have a look at https://cortexmetrics.io/docs/blocks-storage/ and https://cortexmetrics.io/docs/getting-started/getting-started-blocks-storage/ for example configurations that use block storage.
