### ISSUE TITLE
"Chart.yaml Dependencies" are failing

### ISSUE THREAD

**Issue by vikram-yerneni** [cortexproject/cortex-helm-chart#59]
Plain Helm install with the chart is failing on the dependencies in the chart.yaml file:
`My-MacBook-Pro % helm install cortex --namespace cortex -f values.yaml /Users/vikramyerneni/Desktop/repos/cortex-helm-chart
Error: found in Chart.yaml, but missing in charts/ directory: memcached, memcached, memcached
My-MacBook-Pro% `

And the path "https://kubernetes-charts.storage.googleapis.com" in the file don't have any memcached .tgz files or associated path.

**Comment by khaines** [comment]
you may need a `--dependency-update` added to your installation command. When I ran this on my mac after deleting my charts folder, I got the same error you have, but adding the mentioned flag to the installation command downloaded a new copy of the memcached chart
