### ISSUE TITLE
Update Chart to support Cortex 0.3.0

### ISSUE THREAD

**Issue by gramidt** [cortexproject/cortex-helm-chart#6]
**Problem:** This chart is out of date and should be updated to the latest version of Cortex before adding new options and features. 

https://github.com/cortexproject/cortex/releases/tag/v0.3.0

**Comment by amadeus-x1** [comment]
@gramidt Any estimates on how long this will take?

**Comment by beditarun** [comment]
@gramidt Any estimates on how long this will take?

**Comment by tbedi-jnpr** [comment]
@gramidt Any estimates on how long this will take, or is there any other way to use Cortex's helm chart with GCS as backend? Thanks.

**Comment by hairyhenderson** [comment]
As of #25 this chart supports Cortex v1.1.0, so I think this particular issue is no longer relevant!

**Comment by khaines** [comment]
(cleaning up older issues)

this issue is no longer relevant
