### ISSUE TITLE
nginx config options

### ISSUE THREAD

**Issue by rekup** [cortexproject/cortex-helm-chart#72]
It would be nice to have a bit more flexibility in the nginx config for example to define additional directives in the http and/or server context. This could be achieved by adding something like `.Values.nginx.config.additionalHttpConfig` / `.Values.nginx.config.additionalServerConfig` to pass additional directives or by defining a value `.Values.nginx.configRaw` (not sure about the naming of the values) which lets the user overwrite the entire nginx config. Is this something you'd be interested to have in the chart or should we better deploy nginx separately in such a case?

Thanks!

**Comment by cabrinha** [comment]
To add onto this, we should also have a way to use multi-tenancy in Cortex.

Pretty sure we're going to need to pass along headers sent from remote-writes, changing this line here: https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/nginx-config.yaml#L36

**Comment by rekup** [comment]
Multi-tenancy is exactly the reason why we would like to customize the nginx config. We are using client certificate authentication for the tenants and need to extract the tenant id from the certificate and pass it as the `X-Scope-OrgID`.

**Comment by Carmezim** [comment]
It'd be very helpful to be able to do that. Worked around it by forking and editing the chart but can't use the chart with auth enabled

**Comment by RixTmobilender** [comment]
I'm currently finding a need for this while trying to integrate Grafana 8's new ngalert with Cortex.
It seems ["Only single-binary mode is currently supported, and it is not possible to provide a separate URL for the ruler API."](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/create-cortex-loki-managed-rule/#create-a-cortex-or-loki-managed-alerting-rule).

My use case would require adding a snippet like this in order to "trick" Grafana into thinking Cortex is deployed in single-binary mode:
```
   location ~ /api/prom/rules {
      proxy_pass      http://{{ template "cortex.fullname" . }}-ruler.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.config.server.http_listen_port }}$request_uri;
   }
```

**Comment by danfromtitan** [comment]
> Multi-tenancy is exactly the reason why we would like to customize the nginx config. We are using client certificate authentication for the tenants and need to extract the tenant id from the certificate and pass it as the `X-Scope-OrgID`.

I'm curious what field in the client certificate would you use to generate the tenant ID.

**Comment by rekup** [comment]
We currently use the certificates common name as identifier

```
          map  $http_ssl_client_subject_dn  $ssl_client_s_dn_cn {
            default "";
            ~CN=(?<CN>[^,\"]+) $CN;
          }
```

**Comment by ShuzZzle** [comment]
I think most of requested features are now implemented, let us know if you need something else
